/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.AuditLogs

import java.lang.String
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class AuditLogsRecord extends UpdatableRecordImpl[AuditLogsRecord](AuditLogs.AUDIT_LOGS) with Record7[UUID, UUID, String, String, UUID, String, OffsetDateTime] {

  /**
   * Setter for <code>public.audit_logs.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.audit_logs.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.audit_logs.user_id</code>.
   */
  def setUserId(value: UUID): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.audit_logs.user_id</code>.
   */
  def getUserId: UUID = get(1).asInstanceOf[UUID]

  /**
   * Setter for <code>public.audit_logs.action</code>.
   */
  def setAction(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.audit_logs.action</code>.
   */
  def getAction: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>public.audit_logs.entity_type</code>.
   */
  def setEntityType(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.audit_logs.entity_type</code>.
   */
  def getEntityType: String = get(3).asInstanceOf[String]

  /**
   * Setter for <code>public.audit_logs.entity_id</code>.
   */
  def setEntityId(value: UUID): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.audit_logs.entity_id</code>.
   */
  def getEntityId: UUID = get(4).asInstanceOf[UUID]

  /**
   * Setter for <code>public.audit_logs.details</code>.
   */
  def setDetails(value: String): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.audit_logs.details</code>.
   */
  def getDetails: String = get(5).asInstanceOf[String]

  /**
   * Setter for <code>public.audit_logs.timestamp</code>.
   */
  def setTimestamp(value: OffsetDateTime): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.audit_logs.timestamp</code>.
   */
  def getTimestamp: OffsetDateTime = get(6).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record7 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row7[UUID, UUID, String, String, UUID, String, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, UUID, String, String, UUID, String, OffsetDateTime] ]

  override def valuesRow: Row7[UUID, UUID, String, String, UUID, String, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row7[UUID, UUID, String, String, UUID, String, OffsetDateTime] ]
  override def field1: Field[UUID] = AuditLogs.AUDIT_LOGS.ID
  override def field2: Field[UUID] = AuditLogs.AUDIT_LOGS.USER_ID
  override def field3: Field[String] = AuditLogs.AUDIT_LOGS.ACTION
  override def field4: Field[String] = AuditLogs.AUDIT_LOGS.ENTITY_TYPE
  override def field5: Field[UUID] = AuditLogs.AUDIT_LOGS.ENTITY_ID
  override def field6: Field[String] = AuditLogs.AUDIT_LOGS.DETAILS
  override def field7: Field[OffsetDateTime] = AuditLogs.AUDIT_LOGS.TIMESTAMP
  override def component1: UUID = getId
  override def component2: UUID = getUserId
  override def component3: String = getAction
  override def component4: String = getEntityType
  override def component5: UUID = getEntityId
  override def component6: String = getDetails
  override def component7: OffsetDateTime = getTimestamp
  override def value1: UUID = getId
  override def value2: UUID = getUserId
  override def value3: String = getAction
  override def value4: String = getEntityType
  override def value5: UUID = getEntityId
  override def value6: String = getDetails
  override def value7: OffsetDateTime = getTimestamp

  override def value1(value: UUID): AuditLogsRecord = {
    setId(value)
    this
  }

  override def value2(value: UUID): AuditLogsRecord = {
    setUserId(value)
    this
  }

  override def value3(value: String): AuditLogsRecord = {
    setAction(value)
    this
  }

  override def value4(value: String): AuditLogsRecord = {
    setEntityType(value)
    this
  }

  override def value5(value: UUID): AuditLogsRecord = {
    setEntityId(value)
    this
  }

  override def value6(value: String): AuditLogsRecord = {
    setDetails(value)
    this
  }

  override def value7(value: OffsetDateTime): AuditLogsRecord = {
    setTimestamp(value)
    this
  }

  override def values(value1 : UUID, value2 : UUID, value3 : String, value4 : String, value5 : UUID, value6 : String, value7 : OffsetDateTime): AuditLogsRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this
  }

  /**
   * Create a detached, initialised AuditLogsRecord
   */
  def this(id : UUID, userId : UUID, action : String, entityType : String, entityId : UUID, details : String, timestamp : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setUserId(userId)
    this.setAction(action)
    this.setEntityType(entityType)
    this.setEntityId(entityId)
    this.setDetails(details)
    this.setTimestamp(timestamp)
    resetChangedOnNotNull()
  }
}
