/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.ParkingSpaces

import java.lang.String
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class ParkingSpacesRecord extends UpdatableRecordImpl[ParkingSpacesRecord](ParkingSpaces.PARKING_SPACES) with Record9[UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.parking_spaces.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.parking_spaces.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_spaces.lot_id</code>.
   */
  def setLotId(value: UUID): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.parking_spaces.lot_id</code>.
   */
  def getLotId: UUID = get(1).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_spaces.level_id</code>.
   */
  def setLevelId(value: UUID): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.parking_spaces.level_id</code>.
   */
  def getLevelId: UUID = get(2).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_spaces.space_number</code>.
   */
  def setSpaceNumber(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.parking_spaces.space_number</code>.
   */
  def getSpaceNumber: String = get(3).asInstanceOf[String]

  /**
   * Setter for <code>public.parking_spaces.type</code>.
   */
  def setType(value: String): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.parking_spaces.type</code>.
   */
  def getType: String = get(4).asInstanceOf[String]

  /**
   * Setter for <code>public.parking_spaces.status</code>.
   */
  def setStatus(value: String): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.parking_spaces.status</code>.
   */
  def getStatus: String = get(5).asInstanceOf[String]

  /**
   * Setter for <code>public.parking_spaces.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.parking_spaces.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(6).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_spaces.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(7, value)
  }

  /**
   * Getter for <code>public.parking_spaces.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(7).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_spaces.deleted_at</code>.
   */
  def setDeletedAt(value: OffsetDateTime): Unit = {
    set(8, value)
  }

  /**
   * Getter for <code>public.parking_spaces.deleted_at</code>.
   */
  def getDeletedAt: OffsetDateTime = get(8).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record9 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row9[UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row9[UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row9[UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row9[UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = ParkingSpaces.PARKING_SPACES.ID
  override def field2: Field[UUID] = ParkingSpaces.PARKING_SPACES.LOT_ID
  override def field3: Field[UUID] = ParkingSpaces.PARKING_SPACES.LEVEL_ID
  override def field4: Field[String] = ParkingSpaces.PARKING_SPACES.SPACE_NUMBER
  override def field5: Field[String] = ParkingSpaces.PARKING_SPACES.TYPE
  override def field6: Field[String] = ParkingSpaces.PARKING_SPACES.STATUS
  override def field7: Field[OffsetDateTime] = ParkingSpaces.PARKING_SPACES.CREATED_AT
  override def field8: Field[OffsetDateTime] = ParkingSpaces.PARKING_SPACES.UPDATED_AT
  override def field9: Field[OffsetDateTime] = ParkingSpaces.PARKING_SPACES.DELETED_AT
  override def component1: UUID = getId
  override def component2: UUID = getLotId
  override def component3: UUID = getLevelId
  override def component4: String = getSpaceNumber
  override def component5: String = getType
  override def component6: String = getStatus
  override def component7: OffsetDateTime = getCreatedAt
  override def component8: OffsetDateTime = getUpdatedAt
  override def component9: OffsetDateTime = getDeletedAt
  override def value1: UUID = getId
  override def value2: UUID = getLotId
  override def value3: UUID = getLevelId
  override def value4: String = getSpaceNumber
  override def value5: String = getType
  override def value6: String = getStatus
  override def value7: OffsetDateTime = getCreatedAt
  override def value8: OffsetDateTime = getUpdatedAt
  override def value9: OffsetDateTime = getDeletedAt

  override def value1(value: UUID): ParkingSpacesRecord = {
    setId(value)
    this
  }

  override def value2(value: UUID): ParkingSpacesRecord = {
    setLotId(value)
    this
  }

  override def value3(value: UUID): ParkingSpacesRecord = {
    setLevelId(value)
    this
  }

  override def value4(value: String): ParkingSpacesRecord = {
    setSpaceNumber(value)
    this
  }

  override def value5(value: String): ParkingSpacesRecord = {
    setType(value)
    this
  }

  override def value6(value: String): ParkingSpacesRecord = {
    setStatus(value)
    this
  }

  override def value7(value: OffsetDateTime): ParkingSpacesRecord = {
    setCreatedAt(value)
    this
  }

  override def value8(value: OffsetDateTime): ParkingSpacesRecord = {
    setUpdatedAt(value)
    this
  }

  override def value9(value: OffsetDateTime): ParkingSpacesRecord = {
    setDeletedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : UUID, value3 : UUID, value4 : String, value5 : String, value6 : String, value7 : OffsetDateTime, value8 : OffsetDateTime, value9 : OffsetDateTime): ParkingSpacesRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this.value8(value8)
    this.value9(value9)
    this
  }

  /**
   * Create a detached, initialised ParkingSpacesRecord
   */
  def this(id : UUID, lotId : UUID, levelId : UUID, spaceNumber : String, `type` : String, status : String, createdAt : OffsetDateTime, updatedAt : OffsetDateTime, deletedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setLotId(lotId)
    this.setLevelId(levelId)
    this.setSpaceNumber(spaceNumber)
    this.setType(`type`)
    this.setStatus(status)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    this.setDeletedAt(deletedAt)
    resetChangedOnNotNull()
  }
}
