/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.ParkingSessions

import java.lang.Integer
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class ParkingSessionsRecord extends UpdatableRecordImpl[ParkingSessionsRecord](ParkingSessions.PARKING_SESSIONS) with Record9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.parking_sessions.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.parking_sessions.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_sessions.vehicle_id</code>.
   */
  def setVehicleId(value: UUID): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.parking_sessions.vehicle_id</code>.
   */
  def getVehicleId: UUID = get(1).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_sessions.space_id</code>.
   */
  def setSpaceId(value: UUID): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.parking_sessions.space_id</code>.
   */
  def getSpaceId: UUID = get(2).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_sessions.entry_time</code>.
   */
  def setEntryTime(value: OffsetDateTime): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.parking_sessions.entry_time</code>.
   */
  def getEntryTime: OffsetDateTime = get(3).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_sessions.exit_time</code>.
   */
  def setExitTime(value: OffsetDateTime): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.parking_sessions.exit_time</code>.
   */
  def getExitTime: OffsetDateTime = get(4).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_sessions.duration_minutes</code>.
   */
  def setDurationMinutes(value: Integer): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.parking_sessions.duration_minutes</code>.
   */
  def getDurationMinutes: Integer = get(5).asInstanceOf[Integer]

  /**
   * Setter for <code>public.parking_sessions.fee</code>.
   */
  def setFee(value: BigDecimal): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.parking_sessions.fee</code>.
   */
  def getFee: BigDecimal = get(6).asInstanceOf[BigDecimal]

  /**
   * Setter for <code>public.parking_sessions.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(7, value)
  }

  /**
   * Getter for <code>public.parking_sessions.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(7).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_sessions.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(8, value)
  }

  /**
   * Getter for <code>public.parking_sessions.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(8).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record9 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = ParkingSessions.PARKING_SESSIONS.ID
  override def field2: Field[UUID] = ParkingSessions.PARKING_SESSIONS.VEHICLE_ID
  override def field3: Field[UUID] = ParkingSessions.PARKING_SESSIONS.SPACE_ID
  override def field4: Field[OffsetDateTime] = ParkingSessions.PARKING_SESSIONS.ENTRY_TIME
  override def field5: Field[OffsetDateTime] = ParkingSessions.PARKING_SESSIONS.EXIT_TIME
  override def field6: Field[Integer] = ParkingSessions.PARKING_SESSIONS.DURATION_MINUTES
  override def field7: Field[BigDecimal] = ParkingSessions.PARKING_SESSIONS.FEE
  override def field8: Field[OffsetDateTime] = ParkingSessions.PARKING_SESSIONS.CREATED_AT
  override def field9: Field[OffsetDateTime] = ParkingSessions.PARKING_SESSIONS.UPDATED_AT
  override def component1: UUID = getId
  override def component2: UUID = getVehicleId
  override def component3: UUID = getSpaceId
  override def component4: OffsetDateTime = getEntryTime
  override def component5: OffsetDateTime = getExitTime
  override def component6: Integer = getDurationMinutes
  override def component7: BigDecimal = getFee
  override def component8: OffsetDateTime = getCreatedAt
  override def component9: OffsetDateTime = getUpdatedAt
  override def value1: UUID = getId
  override def value2: UUID = getVehicleId
  override def value3: UUID = getSpaceId
  override def value4: OffsetDateTime = getEntryTime
  override def value5: OffsetDateTime = getExitTime
  override def value6: Integer = getDurationMinutes
  override def value7: BigDecimal = getFee
  override def value8: OffsetDateTime = getCreatedAt
  override def value9: OffsetDateTime = getUpdatedAt

  override def value1(value: UUID): ParkingSessionsRecord = {
    setId(value)
    this
  }

  override def value2(value: UUID): ParkingSessionsRecord = {
    setVehicleId(value)
    this
  }

  override def value3(value: UUID): ParkingSessionsRecord = {
    setSpaceId(value)
    this
  }

  override def value4(value: OffsetDateTime): ParkingSessionsRecord = {
    setEntryTime(value)
    this
  }

  override def value5(value: OffsetDateTime): ParkingSessionsRecord = {
    setExitTime(value)
    this
  }

  override def value6(value: Integer): ParkingSessionsRecord = {
    setDurationMinutes(value)
    this
  }

  override def value7(value: BigDecimal): ParkingSessionsRecord = {
    setFee(value)
    this
  }

  override def value8(value: OffsetDateTime): ParkingSessionsRecord = {
    setCreatedAt(value)
    this
  }

  override def value9(value: OffsetDateTime): ParkingSessionsRecord = {
    setUpdatedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : UUID, value3 : UUID, value4 : OffsetDateTime, value5 : OffsetDateTime, value6 : Integer, value7 : BigDecimal, value8 : OffsetDateTime, value9 : OffsetDateTime): ParkingSessionsRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this.value8(value8)
    this.value9(value9)
    this
  }

  /**
   * Create a detached, initialised ParkingSessionsRecord
   */
  def this(id : UUID, vehicleId : UUID, spaceId : UUID, entryTime : OffsetDateTime, exitTime : OffsetDateTime, durationMinutes : Integer, fee : BigDecimal, createdAt : OffsetDateTime, updatedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setVehicleId(vehicleId)
    this.setSpaceId(spaceId)
    this.setEntryTime(entryTime)
    this.setExitTime(exitTime)
    this.setDurationMinutes(durationMinutes)
    this.setFee(fee)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    resetChangedOnNotNull()
  }
}
