/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.ParkingLots

import java.lang.String
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class ParkingLotsRecord extends UpdatableRecordImpl[ParkingLotsRecord](ParkingLots.PARKING_LOTS) with Record6[UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.parking_lots.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.parking_lots.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_lots.name</code>.
   */
  def setName(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.parking_lots.name</code>.
   */
  def getName: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>public.parking_lots.location</code>.
   */
  def setLocation(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.parking_lots.location</code>.
   */
  def getLocation: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>public.parking_lots.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.parking_lots.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(3).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_lots.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.parking_lots.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(4).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_lots.deleted_at</code>.
   */
  def setDeletedAt(value: OffsetDateTime): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.parking_lots.deleted_at</code>.
   */
  def getDeletedAt: OffsetDateTime = get(5).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record6 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row6[UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row6[UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row6[UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row6[UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = ParkingLots.PARKING_LOTS.ID
  override def field2: Field[String] = ParkingLots.PARKING_LOTS.NAME
  override def field3: Field[String] = ParkingLots.PARKING_LOTS.LOCATION
  override def field4: Field[OffsetDateTime] = ParkingLots.PARKING_LOTS.CREATED_AT
  override def field5: Field[OffsetDateTime] = ParkingLots.PARKING_LOTS.UPDATED_AT
  override def field6: Field[OffsetDateTime] = ParkingLots.PARKING_LOTS.DELETED_AT
  override def component1: UUID = getId
  override def component2: String = getName
  override def component3: String = getLocation
  override def component4: OffsetDateTime = getCreatedAt
  override def component5: OffsetDateTime = getUpdatedAt
  override def component6: OffsetDateTime = getDeletedAt
  override def value1: UUID = getId
  override def value2: String = getName
  override def value3: String = getLocation
  override def value4: OffsetDateTime = getCreatedAt
  override def value5: OffsetDateTime = getUpdatedAt
  override def value6: OffsetDateTime = getDeletedAt

  override def value1(value: UUID): ParkingLotsRecord = {
    setId(value)
    this
  }

  override def value2(value: String): ParkingLotsRecord = {
    setName(value)
    this
  }

  override def value3(value: String): ParkingLotsRecord = {
    setLocation(value)
    this
  }

  override def value4(value: OffsetDateTime): ParkingLotsRecord = {
    setCreatedAt(value)
    this
  }

  override def value5(value: OffsetDateTime): ParkingLotsRecord = {
    setUpdatedAt(value)
    this
  }

  override def value6(value: OffsetDateTime): ParkingLotsRecord = {
    setDeletedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : String, value3 : String, value4 : OffsetDateTime, value5 : OffsetDateTime, value6 : OffsetDateTime): ParkingLotsRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this
  }

  /**
   * Create a detached, initialised ParkingLotsRecord
   */
  def this(id : UUID, name : String, location : String, createdAt : OffsetDateTime, updatedAt : OffsetDateTime, deletedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setName(name)
    this.setLocation(location)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    this.setDeletedAt(deletedAt)
    resetChangedOnNotNull()
  }
}
