/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.ParkingLevels

import java.lang.Integer
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class ParkingLevelsRecord extends UpdatableRecordImpl[ParkingLevelsRecord](ParkingLevels.PARKING_LEVELS) with Record5[UUID, UUID, Integer, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.parking_levels.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.parking_levels.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_levels.lot_id</code>.
   */
  def setLotId(value: UUID): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.parking_levels.lot_id</code>.
   */
  def getLotId: UUID = get(1).asInstanceOf[UUID]

  /**
   * Setter for <code>public.parking_levels.level_number</code>.
   */
  def setLevelNumber(value: Integer): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.parking_levels.level_number</code>.
   */
  def getLevelNumber: Integer = get(2).asInstanceOf[Integer]

  /**
   * Setter for <code>public.parking_levels.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.parking_levels.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(3).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.parking_levels.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.parking_levels.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(4).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record5 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row5[UUID, UUID, Integer, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row5[UUID, UUID, Integer, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row5[UUID, UUID, Integer, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row5[UUID, UUID, Integer, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = ParkingLevels.PARKING_LEVELS.ID
  override def field2: Field[UUID] = ParkingLevels.PARKING_LEVELS.LOT_ID
  override def field3: Field[Integer] = ParkingLevels.PARKING_LEVELS.LEVEL_NUMBER
  override def field4: Field[OffsetDateTime] = ParkingLevels.PARKING_LEVELS.CREATED_AT
  override def field5: Field[OffsetDateTime] = ParkingLevels.PARKING_LEVELS.UPDATED_AT
  override def component1: UUID = getId
  override def component2: UUID = getLotId
  override def component3: Integer = getLevelNumber
  override def component4: OffsetDateTime = getCreatedAt
  override def component5: OffsetDateTime = getUpdatedAt
  override def value1: UUID = getId
  override def value2: UUID = getLotId
  override def value3: Integer = getLevelNumber
  override def value4: OffsetDateTime = getCreatedAt
  override def value5: OffsetDateTime = getUpdatedAt

  override def value1(value: UUID): ParkingLevelsRecord = {
    setId(value)
    this
  }

  override def value2(value: UUID): ParkingLevelsRecord = {
    setLotId(value)
    this
  }

  override def value3(value: Integer): ParkingLevelsRecord = {
    setLevelNumber(value)
    this
  }

  override def value4(value: OffsetDateTime): ParkingLevelsRecord = {
    setCreatedAt(value)
    this
  }

  override def value5(value: OffsetDateTime): ParkingLevelsRecord = {
    setUpdatedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : UUID, value3 : Integer, value4 : OffsetDateTime, value5 : OffsetDateTime): ParkingLevelsRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this
  }

  /**
   * Create a detached, initialised ParkingLevelsRecord
   */
  def this(id : UUID, lotId : UUID, levelNumber : Integer, createdAt : OffsetDateTime, updatedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setLotId(lotId)
    this.setLevelNumber(levelNumber)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    resetChangedOnNotNull()
  }
}
