/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.Payments

import java.lang.String
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class PaymentsRecord extends UpdatableRecordImpl[PaymentsRecord](Payments.PAYMENTS) with Record7[UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.payments.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.payments.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.payments.session_id</code>.
   */
  def setSessionId(value: UUID): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.payments.session_id</code>.
   */
  def getSessionId: UUID = get(1).asInstanceOf[UUID]

  /**
   * Setter for <code>public.payments.amount</code>.
   */
  def setAmount(value: BigDecimal): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.payments.amount</code>.
   */
  def getAmount: BigDecimal = get(2).asInstanceOf[BigDecimal]

  /**
   * Setter for <code>public.payments.method</code>.
   */
  def setMethod(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.payments.method</code>.
   */
  def getMethod: String = get(3).asInstanceOf[String]

  /**
   * Setter for <code>public.payments.status</code>.
   */
  def setStatus(value: String): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.payments.status</code>.
   */
  def getStatus: String = get(4).asInstanceOf[String]

  /**
   * Setter for <code>public.payments.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.payments.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(5).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.payments.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.payments.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(6).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record7 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row7[UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row7[UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row7[UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = Payments.PAYMENTS.ID
  override def field2: Field[UUID] = Payments.PAYMENTS.SESSION_ID
  override def field3: Field[BigDecimal] = Payments.PAYMENTS.AMOUNT
  override def field4: Field[String] = Payments.PAYMENTS.METHOD
  override def field5: Field[String] = Payments.PAYMENTS.STATUS
  override def field6: Field[OffsetDateTime] = Payments.PAYMENTS.CREATED_AT
  override def field7: Field[OffsetDateTime] = Payments.PAYMENTS.UPDATED_AT
  override def component1: UUID = getId
  override def component2: UUID = getSessionId
  override def component3: BigDecimal = getAmount
  override def component4: String = getMethod
  override def component5: String = getStatus
  override def component6: OffsetDateTime = getCreatedAt
  override def component7: OffsetDateTime = getUpdatedAt
  override def value1: UUID = getId
  override def value2: UUID = getSessionId
  override def value3: BigDecimal = getAmount
  override def value4: String = getMethod
  override def value5: String = getStatus
  override def value6: OffsetDateTime = getCreatedAt
  override def value7: OffsetDateTime = getUpdatedAt

  override def value1(value: UUID): PaymentsRecord = {
    setId(value)
    this
  }

  override def value2(value: UUID): PaymentsRecord = {
    setSessionId(value)
    this
  }

  override def value3(value: BigDecimal): PaymentsRecord = {
    setAmount(value)
    this
  }

  override def value4(value: String): PaymentsRecord = {
    setMethod(value)
    this
  }

  override def value5(value: String): PaymentsRecord = {
    setStatus(value)
    this
  }

  override def value6(value: OffsetDateTime): PaymentsRecord = {
    setCreatedAt(value)
    this
  }

  override def value7(value: OffsetDateTime): PaymentsRecord = {
    setUpdatedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : UUID, value3 : BigDecimal, value4 : String, value5 : String, value6 : OffsetDateTime, value7 : OffsetDateTime): PaymentsRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this
  }

  /**
   * Create a detached, initialised PaymentsRecord
   */
  def this(id : UUID, sessionId : UUID, amount : BigDecimal, method : String, status : String, createdAt : OffsetDateTime, updatedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setSessionId(sessionId)
    this.setAmount(amount)
    this.setMethod(method)
    this.setStatus(status)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    resetChangedOnNotNull()
  }
}
