/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.PricingRules

import java.lang.String
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class PricingRulesRecord extends UpdatableRecordImpl[PricingRulesRecord](PricingRules.PRICING_RULES) with Record7[UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.pricing_rules.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.pricing_rules.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.pricing_rules.rule_type</code>.
   */
  def setRuleType(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.pricing_rules.rule_type</code>.
   */
  def getRuleType: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>public.pricing_rules.rate</code>.
   */
  def setRate(value: BigDecimal): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.pricing_rules.rate</code>.
   */
  def getRate: BigDecimal = get(2).asInstanceOf[BigDecimal]

  /**
   * Setter for <code>public.pricing_rules.vehicle_type</code>.
   */
  def setVehicleType(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.pricing_rules.vehicle_type</code>.
   */
  def getVehicleType: String = get(3).asInstanceOf[String]

  /**
   * Setter for <code>public.pricing_rules.lot_id</code>.
   */
  def setLotId(value: UUID): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.pricing_rules.lot_id</code>.
   */
  def getLotId: UUID = get(4).asInstanceOf[UUID]

  /**
   * Setter for <code>public.pricing_rules.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.pricing_rules.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(5).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.pricing_rules.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.pricing_rules.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(6).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record7 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row7[UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row7[UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row7[UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = PricingRules.PRICING_RULES.ID
  override def field2: Field[String] = PricingRules.PRICING_RULES.RULE_TYPE
  override def field3: Field[BigDecimal] = PricingRules.PRICING_RULES.RATE
  override def field4: Field[String] = PricingRules.PRICING_RULES.VEHICLE_TYPE
  override def field5: Field[UUID] = PricingRules.PRICING_RULES.LOT_ID
  override def field6: Field[OffsetDateTime] = PricingRules.PRICING_RULES.CREATED_AT
  override def field7: Field[OffsetDateTime] = PricingRules.PRICING_RULES.UPDATED_AT
  override def component1: UUID = getId
  override def component2: String = getRuleType
  override def component3: BigDecimal = getRate
  override def component4: String = getVehicleType
  override def component5: UUID = getLotId
  override def component6: OffsetDateTime = getCreatedAt
  override def component7: OffsetDateTime = getUpdatedAt
  override def value1: UUID = getId
  override def value2: String = getRuleType
  override def value3: BigDecimal = getRate
  override def value4: String = getVehicleType
  override def value5: UUID = getLotId
  override def value6: OffsetDateTime = getCreatedAt
  override def value7: OffsetDateTime = getUpdatedAt

  override def value1(value: UUID): PricingRulesRecord = {
    setId(value)
    this
  }

  override def value2(value: String): PricingRulesRecord = {
    setRuleType(value)
    this
  }

  override def value3(value: BigDecimal): PricingRulesRecord = {
    setRate(value)
    this
  }

  override def value4(value: String): PricingRulesRecord = {
    setVehicleType(value)
    this
  }

  override def value5(value: UUID): PricingRulesRecord = {
    setLotId(value)
    this
  }

  override def value6(value: OffsetDateTime): PricingRulesRecord = {
    setCreatedAt(value)
    this
  }

  override def value7(value: OffsetDateTime): PricingRulesRecord = {
    setUpdatedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : String, value3 : BigDecimal, value4 : String, value5 : UUID, value6 : OffsetDateTime, value7 : OffsetDateTime): PricingRulesRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this
  }

  /**
   * Create a detached, initialised PricingRulesRecord
   */
  def this(id : UUID, ruleType : String, rate : BigDecimal, vehicleType : String, lotId : UUID, createdAt : OffsetDateTime, updatedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setRuleType(ruleType)
    this.setRate(rate)
    this.setVehicleType(vehicleType)
    this.setLotId(lotId)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    resetChangedOnNotNull()
  }
}
