/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.Reservations

import java.lang.String
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class ReservationsRecord extends UpdatableRecordImpl[ReservationsRecord](Reservations.RESERVATIONS) with Record9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.reservations.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.reservations.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.reservations.user_id</code>.
   */
  def setUserId(value: UUID): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.reservations.user_id</code>.
   */
  def getUserId: UUID = get(1).asInstanceOf[UUID]

  /**
   * Setter for <code>public.reservations.space_id</code>.
   */
  def setSpaceId(value: UUID): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.reservations.space_id</code>.
   */
  def getSpaceId: UUID = get(2).asInstanceOf[UUID]

  /**
   * Setter for <code>public.reservations.start_time</code>.
   */
  def setStartTime(value: OffsetDateTime): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.reservations.start_time</code>.
   */
  def getStartTime: OffsetDateTime = get(3).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.reservations.end_time</code>.
   */
  def setEndTime(value: OffsetDateTime): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.reservations.end_time</code>.
   */
  def getEndTime: OffsetDateTime = get(4).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.reservations.status</code>.
   */
  def setStatus(value: String): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.reservations.status</code>.
   */
  def getStatus: String = get(5).asInstanceOf[String]

  /**
   * Setter for <code>public.reservations.fee</code>.
   */
  def setFee(value: BigDecimal): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.reservations.fee</code>.
   */
  def getFee: BigDecimal = get(6).asInstanceOf[BigDecimal]

  /**
   * Setter for <code>public.reservations.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(7, value)
  }

  /**
   * Getter for <code>public.reservations.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(7).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.reservations.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(8, value)
  }

  /**
   * Getter for <code>public.reservations.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(8).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record9 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = Reservations.RESERVATIONS.ID
  override def field2: Field[UUID] = Reservations.RESERVATIONS.USER_ID
  override def field3: Field[UUID] = Reservations.RESERVATIONS.SPACE_ID
  override def field4: Field[OffsetDateTime] = Reservations.RESERVATIONS.START_TIME
  override def field5: Field[OffsetDateTime] = Reservations.RESERVATIONS.END_TIME
  override def field6: Field[String] = Reservations.RESERVATIONS.STATUS
  override def field7: Field[BigDecimal] = Reservations.RESERVATIONS.FEE
  override def field8: Field[OffsetDateTime] = Reservations.RESERVATIONS.CREATED_AT
  override def field9: Field[OffsetDateTime] = Reservations.RESERVATIONS.UPDATED_AT
  override def component1: UUID = getId
  override def component2: UUID = getUserId
  override def component3: UUID = getSpaceId
  override def component4: OffsetDateTime = getStartTime
  override def component5: OffsetDateTime = getEndTime
  override def component6: String = getStatus
  override def component7: BigDecimal = getFee
  override def component8: OffsetDateTime = getCreatedAt
  override def component9: OffsetDateTime = getUpdatedAt
  override def value1: UUID = getId
  override def value2: UUID = getUserId
  override def value3: UUID = getSpaceId
  override def value4: OffsetDateTime = getStartTime
  override def value5: OffsetDateTime = getEndTime
  override def value6: String = getStatus
  override def value7: BigDecimal = getFee
  override def value8: OffsetDateTime = getCreatedAt
  override def value9: OffsetDateTime = getUpdatedAt

  override def value1(value: UUID): ReservationsRecord = {
    setId(value)
    this
  }

  override def value2(value: UUID): ReservationsRecord = {
    setUserId(value)
    this
  }

  override def value3(value: UUID): ReservationsRecord = {
    setSpaceId(value)
    this
  }

  override def value4(value: OffsetDateTime): ReservationsRecord = {
    setStartTime(value)
    this
  }

  override def value5(value: OffsetDateTime): ReservationsRecord = {
    setEndTime(value)
    this
  }

  override def value6(value: String): ReservationsRecord = {
    setStatus(value)
    this
  }

  override def value7(value: BigDecimal): ReservationsRecord = {
    setFee(value)
    this
  }

  override def value8(value: OffsetDateTime): ReservationsRecord = {
    setCreatedAt(value)
    this
  }

  override def value9(value: OffsetDateTime): ReservationsRecord = {
    setUpdatedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : UUID, value3 : UUID, value4 : OffsetDateTime, value5 : OffsetDateTime, value6 : String, value7 : BigDecimal, value8 : OffsetDateTime, value9 : OffsetDateTime): ReservationsRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this.value8(value8)
    this.value9(value9)
    this
  }

  /**
   * Create a detached, initialised ReservationsRecord
   */
  def this(id : UUID, userId : UUID, spaceId : UUID, startTime : OffsetDateTime, endTime : OffsetDateTime, status : String, fee : BigDecimal, createdAt : OffsetDateTime, updatedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setUserId(userId)
    this.setSpaceId(spaceId)
    this.setStartTime(startTime)
    this.setEndTime(endTime)
    this.setStatus(status)
    this.setFee(fee)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    resetChangedOnNotNull()
  }
}
