/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.Roles

import java.lang.String
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class RolesRecord extends UpdatableRecordImpl[RolesRecord](Roles.ROLES) with Record3[UUID, String, String] {

  /**
   * Setter for <code>public.roles.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.roles.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.roles.name</code>.
   */
  def setName(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.roles.name</code>.
   */
  def getName: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>public.roles.description</code>.
   */
  def setDescription(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.roles.description</code>.
   */
  def getDescription: String = get(2).asInstanceOf[String]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row3[UUID, String, String] = super.fieldsRow.asInstanceOf[ Row3[UUID, String, String] ]

  override def valuesRow: Row3[UUID, String, String] = super.valuesRow.asInstanceOf[ Row3[UUID, String, String] ]
  override def field1: Field[UUID] = Roles.ROLES.ID
  override def field2: Field[String] = Roles.ROLES.NAME
  override def field3: Field[String] = Roles.ROLES.DESCRIPTION
  override def component1: UUID = getId
  override def component2: String = getName
  override def component3: String = getDescription
  override def value1: UUID = getId
  override def value2: String = getName
  override def value3: String = getDescription

  override def value1(value: UUID): RolesRecord = {
    setId(value)
    this
  }

  override def value2(value: String): RolesRecord = {
    setName(value)
    this
  }

  override def value3(value: String): RolesRecord = {
    setDescription(value)
    this
  }

  override def values(value1 : UUID, value2 : String, value3 : String): RolesRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this
  }

  /**
   * Create a detached, initialised RolesRecord
   */
  def this(id : UUID, name : String, description : String) = {
    this()

    this.setId(id)
    this.setName(name)
    this.setDescription(description)
    resetChangedOnNotNull()
  }
}
