/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.RolePermissions

import java.util.UUID

import org.jooq.Field
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class RolePermissionsRecord extends UpdatableRecordImpl[RolePermissionsRecord](RolePermissions.ROLE_PERMISSIONS) with Record2[UUID, UUID] {

  /**
   * Setter for <code>public.role_permissions.role_id</code>.
   */
  def setRoleId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.role_permissions.role_id</code>.
   */
  def getRoleId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.role_permissions.permission_id</code>.
   */
  def setPermissionId(value: UUID): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.role_permissions.permission_id</code>.
   */
  def getPermissionId: UUID = get(1).asInstanceOf[UUID]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record2[UUID, UUID] = super.key.asInstanceOf[ Record2[UUID, UUID] ]

  // -------------------------------------------------------------------------
  // Record2 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row2[UUID, UUID] = super.fieldsRow.asInstanceOf[ Row2[UUID, UUID] ]

  override def valuesRow: Row2[UUID, UUID] = super.valuesRow.asInstanceOf[ Row2[UUID, UUID] ]
  override def field1: Field[UUID] = RolePermissions.ROLE_PERMISSIONS.ROLE_ID
  override def field2: Field[UUID] = RolePermissions.ROLE_PERMISSIONS.PERMISSION_ID
  override def component1: UUID = getRoleId
  override def component2: UUID = getPermissionId
  override def value1: UUID = getRoleId
  override def value2: UUID = getPermissionId

  override def value1(value: UUID): RolePermissionsRecord = {
    setRoleId(value)
    this
  }

  override def value2(value: UUID): RolePermissionsRecord = {
    setPermissionId(value)
    this
  }

  override def values(value1 : UUID, value2 : UUID): RolePermissionsRecord = {
    this.value1(value1)
    this.value2(value2)
    this
  }

  /**
   * Create a detached, initialised RolePermissionsRecord
   */
  def this(roleId : UUID, permissionId : UUID) = {
    this()

    this.setRoleId(roleId)
    this.setPermissionId(permissionId)
    resetChangedOnNotNull()
  }
}
