/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.Users

import java.lang.String
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class UsersRecord extends UpdatableRecordImpl[UsersRecord](Users.USERS) with Record8[UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID] {

  /**
   * Setter for <code>public.users.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.users.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.users.name</code>.
   */
  def setName(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.users.name</code>.
   */
  def getName: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>public.users.email</code>.
   */
  def setEmail(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.users.email</code>.
   */
  def getEmail: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>public.users.password_hash</code>.
   */
  def setPasswordHash(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.users.password_hash</code>.
   */
  def getPasswordHash: String = get(3).asInstanceOf[String]

  /**
   * Setter for <code>public.users.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.users.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(4).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.users.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.users.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(5).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.users.deleted_at</code>.
   */
  def setDeletedAt(value: OffsetDateTime): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.users.deleted_at</code>.
   */
  def getDeletedAt: OffsetDateTime = get(6).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.users.role_id</code>.
   */
  def setRoleId(value: UUID): Unit = {
    set(7, value)
  }

  /**
   * Getter for <code>public.users.role_id</code>.
   */
  def getRoleId: UUID = get(7).asInstanceOf[UUID]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row8[UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID] = super.fieldsRow.asInstanceOf[ Row8[UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID] ]

  override def valuesRow: Row8[UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID] = super.valuesRow.asInstanceOf[ Row8[UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID] ]
  override def field1: Field[UUID] = Users.USERS.ID
  override def field2: Field[String] = Users.USERS.NAME
  override def field3: Field[String] = Users.USERS.EMAIL
  override def field4: Field[String] = Users.USERS.PASSWORD_HASH
  override def field5: Field[OffsetDateTime] = Users.USERS.CREATED_AT
  override def field6: Field[OffsetDateTime] = Users.USERS.UPDATED_AT
  override def field7: Field[OffsetDateTime] = Users.USERS.DELETED_AT
  override def field8: Field[UUID] = Users.USERS.ROLE_ID
  override def component1: UUID = getId
  override def component2: String = getName
  override def component3: String = getEmail
  override def component4: String = getPasswordHash
  override def component5: OffsetDateTime = getCreatedAt
  override def component6: OffsetDateTime = getUpdatedAt
  override def component7: OffsetDateTime = getDeletedAt
  override def component8: UUID = getRoleId
  override def value1: UUID = getId
  override def value2: String = getName
  override def value3: String = getEmail
  override def value4: String = getPasswordHash
  override def value5: OffsetDateTime = getCreatedAt
  override def value6: OffsetDateTime = getUpdatedAt
  override def value7: OffsetDateTime = getDeletedAt
  override def value8: UUID = getRoleId

  override def value1(value: UUID): UsersRecord = {
    setId(value)
    this
  }

  override def value2(value: String): UsersRecord = {
    setName(value)
    this
  }

  override def value3(value: String): UsersRecord = {
    setEmail(value)
    this
  }

  override def value4(value: String): UsersRecord = {
    setPasswordHash(value)
    this
  }

  override def value5(value: OffsetDateTime): UsersRecord = {
    setCreatedAt(value)
    this
  }

  override def value6(value: OffsetDateTime): UsersRecord = {
    setUpdatedAt(value)
    this
  }

  override def value7(value: OffsetDateTime): UsersRecord = {
    setDeletedAt(value)
    this
  }

  override def value8(value: UUID): UsersRecord = {
    setRoleId(value)
    this
  }

  override def values(value1 : UUID, value2 : String, value3 : String, value4 : String, value5 : OffsetDateTime, value6 : OffsetDateTime, value7 : OffsetDateTime, value8 : UUID): UsersRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this.value8(value8)
    this
  }

  /**
   * Create a detached, initialised UsersRecord
   */
  def this(id : UUID, name : String, email : String, passwordHash : String, createdAt : OffsetDateTime, updatedAt : OffsetDateTime, deletedAt : OffsetDateTime, roleId : UUID) = {
    this()

    this.setId(id)
    this.setName(name)
    this.setEmail(email)
    this.setPasswordHash(passwordHash)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    this.setDeletedAt(deletedAt)
    this.setRoleId(roleId)
    resetChangedOnNotNull()
  }
}
