/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables.records


import com.metropolisparking.jooq.tables.Vehicles

import java.lang.String
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class VehiclesRecord extends UpdatableRecordImpl[VehiclesRecord](Vehicles.VEHICLES) with Record7[UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime] {

  /**
   * Setter for <code>public.vehicles.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.vehicles.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.vehicles.plate_number</code>.
   */
  def setPlateNumber(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.vehicles.plate_number</code>.
   */
  def getPlateNumber: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>public.vehicles.type</code>.
   */
  def setType(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.vehicles.type</code>.
   */
  def getType: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>public.vehicles.owner_id</code>.
   */
  def setOwnerId(value: UUID): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.vehicles.owner_id</code>.
   */
  def getOwnerId: UUID = get(3).asInstanceOf[UUID]

  /**
   * Setter for <code>public.vehicles.created_at</code>.
   */
  def setCreatedAt(value: OffsetDateTime): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.vehicles.created_at</code>.
   */
  def getCreatedAt: OffsetDateTime = get(4).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.vehicles.updated_at</code>.
   */
  def setUpdatedAt(value: OffsetDateTime): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.vehicles.updated_at</code>.
   */
  def getUpdatedAt: OffsetDateTime = get(5).asInstanceOf[OffsetDateTime]

  /**
   * Setter for <code>public.vehicles.deleted_at</code>.
   */
  def setDeletedAt(value: OffsetDateTime): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.vehicles.deleted_at</code>.
   */
  def getDeletedAt: OffsetDateTime = get(6).asInstanceOf[OffsetDateTime]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  // -------------------------------------------------------------------------
  // Record7 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow: Row7[UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]

  override def valuesRow: Row7[UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.valuesRow.asInstanceOf[ Row7[UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]
  override def field1: Field[UUID] = Vehicles.VEHICLES.ID
  override def field2: Field[String] = Vehicles.VEHICLES.PLATE_NUMBER
  override def field3: Field[String] = Vehicles.VEHICLES.TYPE
  override def field4: Field[UUID] = Vehicles.VEHICLES.OWNER_ID
  override def field5: Field[OffsetDateTime] = Vehicles.VEHICLES.CREATED_AT
  override def field6: Field[OffsetDateTime] = Vehicles.VEHICLES.UPDATED_AT
  override def field7: Field[OffsetDateTime] = Vehicles.VEHICLES.DELETED_AT
  override def component1: UUID = getId
  override def component2: String = getPlateNumber
  override def component3: String = getType
  override def component4: UUID = getOwnerId
  override def component5: OffsetDateTime = getCreatedAt
  override def component6: OffsetDateTime = getUpdatedAt
  override def component7: OffsetDateTime = getDeletedAt
  override def value1: UUID = getId
  override def value2: String = getPlateNumber
  override def value3: String = getType
  override def value4: UUID = getOwnerId
  override def value5: OffsetDateTime = getCreatedAt
  override def value6: OffsetDateTime = getUpdatedAt
  override def value7: OffsetDateTime = getDeletedAt

  override def value1(value: UUID): VehiclesRecord = {
    setId(value)
    this
  }

  override def value2(value: String): VehiclesRecord = {
    setPlateNumber(value)
    this
  }

  override def value3(value: String): VehiclesRecord = {
    setType(value)
    this
  }

  override def value4(value: UUID): VehiclesRecord = {
    setOwnerId(value)
    this
  }

  override def value5(value: OffsetDateTime): VehiclesRecord = {
    setCreatedAt(value)
    this
  }

  override def value6(value: OffsetDateTime): VehiclesRecord = {
    setUpdatedAt(value)
    this
  }

  override def value7(value: OffsetDateTime): VehiclesRecord = {
    setDeletedAt(value)
    this
  }

  override def values(value1 : UUID, value2 : String, value3 : String, value4 : UUID, value5 : OffsetDateTime, value6 : OffsetDateTime, value7 : OffsetDateTime): VehiclesRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this
  }

  /**
   * Create a detached, initialised VehiclesRecord
   */
  def this(id : UUID, plateNumber : String, `type` : String, ownerId : UUID, createdAt : OffsetDateTime, updatedAt : OffsetDateTime, deletedAt : OffsetDateTime) = {
    this()

    this.setId(id)
    this.setPlateNumber(plateNumber)
    this.setType(`type`)
    this.setOwnerId(ownerId)
    this.setCreatedAt(createdAt)
    this.setUpdatedAt(updatedAt)
    this.setDeletedAt(deletedAt)
    resetChangedOnNotNull()
  }
}
