/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.AuditLogsRecord

import java.lang.Class
import java.lang.String
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object AuditLogs {

  /**
   * The reference instance of <code>public.audit_logs</code>
   */
  val AUDIT_LOGS = new AuditLogs
}

/**
 * This class is generated by jOOQ.
 */
class AuditLogs(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, AuditLogsRecord],
  aliased: Table[AuditLogsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[AuditLogsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[AuditLogsRecord] = classOf[AuditLogsRecord]

  /**
   * The column <code>public.audit_logs.id</code>.
   */
  val ID: TableField[AuditLogsRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.audit_logs.user_id</code>.
   */
  val USER_ID: TableField[AuditLogsRecord, UUID] = createField(DSL.name("user_id"), SQLDataType.UUID, "")

  /**
   * The column <code>public.audit_logs.action</code>.
   */
  val ACTION: TableField[AuditLogsRecord, String] = createField(DSL.name("action"), SQLDataType.VARCHAR(100).nullable(false), "")

  /**
   * The column <code>public.audit_logs.entity_type</code>.
   */
  val ENTITY_TYPE: TableField[AuditLogsRecord, String] = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.audit_logs.entity_id</code>.
   */
  val ENTITY_ID: TableField[AuditLogsRecord, UUID] = createField(DSL.name("entity_id"), SQLDataType.UUID, "")

  /**
   * The column <code>public.audit_logs.details</code>.
   */
  val DETAILS: TableField[AuditLogsRecord, String] = createField(DSL.name("details"), SQLDataType.CLOB, "")

  /**
   * The column <code>public.audit_logs.timestamp</code>.
   */
  val TIMESTAMP: TableField[AuditLogsRecord, OffsetDateTime] = createField(DSL.name("timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  private def this(alias: Name, aliased: Table[AuditLogsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.audit_logs</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.AuditLogs.AUDIT_LOGS)

  /**
   * Create an aliased <code>public.audit_logs</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.AuditLogs.AUDIT_LOGS)

  /**
   * Create a <code>public.audit_logs</code> table reference
   */
  def this() = this(DSL.name("audit_logs"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, AuditLogsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.AuditLogs.AUDIT_LOGS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[AuditLogsRecord] = Keys.AUDIT_LOGS_PKEY

  override def getReferences: List[ ForeignKey[AuditLogsRecord, _] ] = Arrays.asList[ ForeignKey[AuditLogsRecord, _] ](Keys.AUDIT_LOGS__AUDIT_LOGS_USER_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.users</code> table.
   */
  lazy val users: Users = { new Users(this, Keys.AUDIT_LOGS__AUDIT_LOGS_USER_ID_FKEY) }
  override def as(alias: String): AuditLogs = new AuditLogs(DSL.name(alias), this)
  override def as(alias: Name): AuditLogs = new AuditLogs(alias, this)
  override def as(alias: Table[_]): AuditLogs = new AuditLogs(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): AuditLogs = new AuditLogs(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): AuditLogs = new AuditLogs(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): AuditLogs = new AuditLogs(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row7 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row7[UUID, UUID, String, String, UUID, String, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, UUID, String, String, UUID, String, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, UUID, String, String, UUID, String, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, UUID, String, String, UUID, String, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))
}
