/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.ParkingSessionsRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object ParkingSessions {

  /**
   * The reference instance of <code>public.parking_sessions</code>
   */
  val PARKING_SESSIONS = new ParkingSessions
}

/**
 * This class is generated by jOOQ.
 */
class ParkingSessions(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, ParkingSessionsRecord],
  aliased: Table[ParkingSessionsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[ParkingSessionsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[ParkingSessionsRecord] = classOf[ParkingSessionsRecord]

  /**
   * The column <code>public.parking_sessions.id</code>.
   */
  val ID: TableField[ParkingSessionsRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.parking_sessions.vehicle_id</code>.
   */
  val VEHICLE_ID: TableField[ParkingSessionsRecord, UUID] = createField(DSL.name("vehicle_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.parking_sessions.space_id</code>.
   */
  val SPACE_ID: TableField[ParkingSessionsRecord, UUID] = createField(DSL.name("space_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.parking_sessions.entry_time</code>.
   */
  val ENTRY_TIME: TableField[ParkingSessionsRecord, OffsetDateTime] = createField(DSL.name("entry_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), "")

  /**
   * The column <code>public.parking_sessions.exit_time</code>.
   */
  val EXIT_TIME: TableField[ParkingSessionsRecord, OffsetDateTime] = createField(DSL.name("exit_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), "")

  /**
   * The column <code>public.parking_sessions.duration_minutes</code>.
   */
  val DURATION_MINUTES: TableField[ParkingSessionsRecord, Integer] = createField(DSL.name("duration_minutes"), SQLDataType.INTEGER, "")

  /**
   * The column <code>public.parking_sessions.fee</code>.
   */
  val FEE: TableField[ParkingSessionsRecord, BigDecimal] = createField(DSL.name("fee"), SQLDataType.NUMERIC(10, 2), "")

  /**
   * The column <code>public.parking_sessions.created_at</code>.
   */
  val CREATED_AT: TableField[ParkingSessionsRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.parking_sessions.updated_at</code>.
   */
  val UPDATED_AT: TableField[ParkingSessionsRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  private def this(alias: Name, aliased: Table[ParkingSessionsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.parking_sessions</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.ParkingSessions.PARKING_SESSIONS)

  /**
   * Create an aliased <code>public.parking_sessions</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.ParkingSessions.PARKING_SESSIONS)

  /**
   * Create a <code>public.parking_sessions</code> table reference
   */
  def this() = this(DSL.name("parking_sessions"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, ParkingSessionsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.ParkingSessions.PARKING_SESSIONS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[ParkingSessionsRecord] = Keys.PARKING_SESSIONS_PKEY

  override def getReferences: List[ ForeignKey[ParkingSessionsRecord, _] ] = Arrays.asList[ ForeignKey[ParkingSessionsRecord, _] ](Keys.PARKING_SESSIONS__PARKING_SESSIONS_VEHICLE_ID_FKEY, Keys.PARKING_SESSIONS__PARKING_SESSIONS_SPACE_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.vehicles</code> table.
   */
  lazy val vehicles: Vehicles = { new Vehicles(this, Keys.PARKING_SESSIONS__PARKING_SESSIONS_VEHICLE_ID_FKEY) }

  /**
   * Get the implicit join path to the <code>public.parking_spaces</code> table.
   */
  lazy val parkingSpaces: ParkingSpaces = { new ParkingSpaces(this, Keys.PARKING_SESSIONS__PARKING_SESSIONS_SPACE_ID_FKEY) }
  override def as(alias: String): ParkingSessions = new ParkingSessions(DSL.name(alias), this)
  override def as(alias: Name): ParkingSessions = new ParkingSessions(alias, this)
  override def as(alias: Table[_]): ParkingSessions = new ParkingSessions(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): ParkingSessions = new ParkingSessions(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): ParkingSessions = new ParkingSessions(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): ParkingSessions = new ParkingSessions(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row9 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8(), r.value9()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, BigDecimal, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8(), r.value9()))
}
