/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.ParkingLotsRecord

import java.lang.Class
import java.lang.String
import java.time.OffsetDateTime
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object ParkingLots {

  /**
   * The reference instance of <code>public.parking_lots</code>
   */
  val PARKING_LOTS = new ParkingLots
}

/**
 * This class is generated by jOOQ.
 */
class ParkingLots(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, ParkingLotsRecord],
  aliased: Table[ParkingLotsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[ParkingLotsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[ParkingLotsRecord] = classOf[ParkingLotsRecord]

  /**
   * The column <code>public.parking_lots.id</code>.
   */
  val ID: TableField[ParkingLotsRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.parking_lots.name</code>.
   */
  val NAME: TableField[ParkingLotsRecord, String] = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), "")

  /**
   * The column <code>public.parking_lots.location</code>.
   */
  val LOCATION: TableField[ParkingLotsRecord, String] = createField(DSL.name("location"), SQLDataType.VARCHAR(255).nullable(false), "")

  /**
   * The column <code>public.parking_lots.created_at</code>.
   */
  val CREATED_AT: TableField[ParkingLotsRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.parking_lots.updated_at</code>.
   */
  val UPDATED_AT: TableField[ParkingLotsRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.parking_lots.deleted_at</code>.
   */
  val DELETED_AT: TableField[ParkingLotsRecord, OffsetDateTime] = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), "")

  private def this(alias: Name, aliased: Table[ParkingLotsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.parking_lots</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.ParkingLots.PARKING_LOTS)

  /**
   * Create an aliased <code>public.parking_lots</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.ParkingLots.PARKING_LOTS)

  /**
   * Create a <code>public.parking_lots</code> table reference
   */
  def this() = this(DSL.name("parking_lots"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, ParkingLotsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.ParkingLots.PARKING_LOTS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[ParkingLotsRecord] = Keys.PARKING_LOTS_PKEY
  override def as(alias: String): ParkingLots = new ParkingLots(DSL.name(alias), this)
  override def as(alias: Name): ParkingLots = new ParkingLots(alias, this)
  override def as(alias: Table[_]): ParkingLots = new ParkingLots(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): ParkingLots = new ParkingLots(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): ParkingLots = new ParkingLots(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): ParkingLots = new ParkingLots(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row6 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row6[UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row6[UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6()))
}
