/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.ParkingSpacesRecord

import java.lang.Class
import java.lang.String
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object ParkingSpaces {

  /**
   * The reference instance of <code>public.parking_spaces</code>
   */
  val PARKING_SPACES = new ParkingSpaces
}

/**
 * This class is generated by jOOQ.
 */
class ParkingSpaces(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, ParkingSpacesRecord],
  aliased: Table[ParkingSpacesRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[ParkingSpacesRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[ParkingSpacesRecord] = classOf[ParkingSpacesRecord]

  /**
   * The column <code>public.parking_spaces.id</code>.
   */
  val ID: TableField[ParkingSpacesRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.parking_spaces.lot_id</code>.
   */
  val LOT_ID: TableField[ParkingSpacesRecord, UUID] = createField(DSL.name("lot_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.parking_spaces.level_id</code>.
   */
  val LEVEL_ID: TableField[ParkingSpacesRecord, UUID] = createField(DSL.name("level_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.parking_spaces.space_number</code>.
   */
  val SPACE_NUMBER: TableField[ParkingSpacesRecord, String] = createField(DSL.name("space_number"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.parking_spaces.type</code>.
   */
  val TYPE: TableField[ParkingSpacesRecord, String] = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.parking_spaces.status</code>.
   */
  val STATUS: TableField[ParkingSpacesRecord, String] = createField(DSL.name("status"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.parking_spaces.created_at</code>.
   */
  val CREATED_AT: TableField[ParkingSpacesRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.parking_spaces.updated_at</code>.
   */
  val UPDATED_AT: TableField[ParkingSpacesRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.parking_spaces.deleted_at</code>.
   */
  val DELETED_AT: TableField[ParkingSpacesRecord, OffsetDateTime] = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), "")

  private def this(alias: Name, aliased: Table[ParkingSpacesRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.parking_spaces</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.ParkingSpaces.PARKING_SPACES)

  /**
   * Create an aliased <code>public.parking_spaces</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.ParkingSpaces.PARKING_SPACES)

  /**
   * Create a <code>public.parking_spaces</code> table reference
   */
  def this() = this(DSL.name("parking_spaces"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, ParkingSpacesRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.ParkingSpaces.PARKING_SPACES, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[ParkingSpacesRecord] = Keys.PARKING_SPACES_PKEY

  override def getUniqueKeys: List[ UniqueKey[ParkingSpacesRecord] ] = Arrays.asList[ UniqueKey[ParkingSpacesRecord] ](Keys.PARKING_SPACES_LEVEL_ID_SPACE_NUMBER_KEY)

  override def getReferences: List[ ForeignKey[ParkingSpacesRecord, _] ] = Arrays.asList[ ForeignKey[ParkingSpacesRecord, _] ](Keys.PARKING_SPACES__PARKING_SPACES_LOT_ID_FKEY, Keys.PARKING_SPACES__PARKING_SPACES_LEVEL_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.parking_lots</code> table.
   */
  lazy val parkingLots: ParkingLots = { new ParkingLots(this, Keys.PARKING_SPACES__PARKING_SPACES_LOT_ID_FKEY) }

  /**
   * Get the implicit join path to the <code>public.parking_levels</code> table.
   */
  lazy val parkingLevels: ParkingLevels = { new ParkingLevels(this, Keys.PARKING_SPACES__PARKING_SPACES_LEVEL_ID_FKEY) }
  override def as(alias: String): ParkingSpaces = new ParkingSpaces(DSL.name(alias), this)
  override def as(alias: Name): ParkingSpaces = new ParkingSpaces(alias, this)
  override def as(alias: Table[_]): ParkingSpaces = new ParkingSpaces(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): ParkingSpaces = new ParkingSpaces(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): ParkingSpaces = new ParkingSpaces(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): ParkingSpaces = new ParkingSpaces(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row9 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row9[UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row9[UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8(), r.value9()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, UUID, UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8(), r.value9()))
}
