/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.ParkingLevelsRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object ParkingLevels {

  /**
   * The reference instance of <code>public.parking_levels</code>
   */
  val PARKING_LEVELS = new ParkingLevels
}

/**
 * This class is generated by jOOQ.
 */
class ParkingLevels(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, ParkingLevelsRecord],
  aliased: Table[ParkingLevelsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[ParkingLevelsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[ParkingLevelsRecord] = classOf[ParkingLevelsRecord]

  /**
   * The column <code>public.parking_levels.id</code>.
   */
  val ID: TableField[ParkingLevelsRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.parking_levels.lot_id</code>.
   */
  val LOT_ID: TableField[ParkingLevelsRecord, UUID] = createField(DSL.name("lot_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.parking_levels.level_number</code>.
   */
  val LEVEL_NUMBER: TableField[ParkingLevelsRecord, Integer] = createField(DSL.name("level_number"), SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>public.parking_levels.created_at</code>.
   */
  val CREATED_AT: TableField[ParkingLevelsRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.parking_levels.updated_at</code>.
   */
  val UPDATED_AT: TableField[ParkingLevelsRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  private def this(alias: Name, aliased: Table[ParkingLevelsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.parking_levels</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.ParkingLevels.PARKING_LEVELS)

  /**
   * Create an aliased <code>public.parking_levels</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.ParkingLevels.PARKING_LEVELS)

  /**
   * Create a <code>public.parking_levels</code> table reference
   */
  def this() = this(DSL.name("parking_levels"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, ParkingLevelsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.ParkingLevels.PARKING_LEVELS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[ParkingLevelsRecord] = Keys.PARKING_LEVELS_PKEY

  override def getUniqueKeys: List[ UniqueKey[ParkingLevelsRecord] ] = Arrays.asList[ UniqueKey[ParkingLevelsRecord] ](Keys.PARKING_LEVELS_LOT_ID_LEVEL_NUMBER_KEY)

  override def getReferences: List[ ForeignKey[ParkingLevelsRecord, _] ] = Arrays.asList[ ForeignKey[ParkingLevelsRecord, _] ](Keys.PARKING_LEVELS__PARKING_LEVELS_LOT_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.parking_lots</code> table.
   */
  lazy val parkingLots: ParkingLots = { new ParkingLots(this, Keys.PARKING_LEVELS__PARKING_LEVELS_LOT_ID_FKEY) }
  override def as(alias: String): ParkingLevels = new ParkingLevels(DSL.name(alias), this)
  override def as(alias: Name): ParkingLevels = new ParkingLevels(alias, this)
  override def as(alias: Table[_]): ParkingLevels = new ParkingLevels(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): ParkingLevels = new ParkingLevels(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): ParkingLevels = new ParkingLevels(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): ParkingLevels = new ParkingLevels(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row5 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row5[UUID, UUID, Integer, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row5[UUID, UUID, Integer, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, UUID, Integer, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, UUID, Integer, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5()))
}
