/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.PaymentsRecord

import java.lang.Class
import java.lang.String
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object Payments {

  /**
   * The reference instance of <code>public.payments</code>
   */
  val PAYMENTS = new Payments
}

/**
 * This class is generated by jOOQ.
 */
class Payments(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, PaymentsRecord],
  aliased: Table[PaymentsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[PaymentsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[PaymentsRecord] = classOf[PaymentsRecord]

  /**
   * The column <code>public.payments.id</code>.
   */
  val ID: TableField[PaymentsRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.payments.session_id</code>.
   */
  val SESSION_ID: TableField[PaymentsRecord, UUID] = createField(DSL.name("session_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.payments.amount</code>.
   */
  val AMOUNT: TableField[PaymentsRecord, BigDecimal] = createField(DSL.name("amount"), SQLDataType.NUMERIC(10, 2).nullable(false), "")

  /**
   * The column <code>public.payments.method</code>.
   */
  val METHOD: TableField[PaymentsRecord, String] = createField(DSL.name("method"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.payments.status</code>.
   */
  val STATUS: TableField[PaymentsRecord, String] = createField(DSL.name("status"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.payments.created_at</code>.
   */
  val CREATED_AT: TableField[PaymentsRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.payments.updated_at</code>.
   */
  val UPDATED_AT: TableField[PaymentsRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  private def this(alias: Name, aliased: Table[PaymentsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.payments</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.Payments.PAYMENTS)

  /**
   * Create an aliased <code>public.payments</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.Payments.PAYMENTS)

  /**
   * Create a <code>public.payments</code> table reference
   */
  def this() = this(DSL.name("payments"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, PaymentsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.Payments.PAYMENTS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[PaymentsRecord] = Keys.PAYMENTS_PKEY

  override def getReferences: List[ ForeignKey[PaymentsRecord, _] ] = Arrays.asList[ ForeignKey[PaymentsRecord, _] ](Keys.PAYMENTS__PAYMENTS_SESSION_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.parking_sessions</code>
   * table.
   */
  lazy val parkingSessions: ParkingSessions = { new ParkingSessions(this, Keys.PAYMENTS__PAYMENTS_SESSION_ID_FKEY) }
  override def as(alias: String): Payments = new Payments(DSL.name(alias), this)
  override def as(alias: Name): Payments = new Payments(alias, this)
  override def as(alias: Table[_]): Payments = new Payments(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): Payments = new Payments(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): Payments = new Payments(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): Payments = new Payments(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row7 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row7[UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, UUID, BigDecimal, String, String, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))
}
