/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.PermissionsRecord

import java.lang.Class
import java.lang.String
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object Permissions {

  /**
   * The reference instance of <code>public.permissions</code>
   */
  val PERMISSIONS = new Permissions
}

/**
 * This class is generated by jOOQ.
 */
class Permissions(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, PermissionsRecord],
  aliased: Table[PermissionsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[PermissionsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[PermissionsRecord] = classOf[PermissionsRecord]

  /**
   * The column <code>public.permissions.id</code>.
   */
  val ID: TableField[PermissionsRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.permissions.name</code>.
   */
  val NAME: TableField[PermissionsRecord, String] = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), "")

  /**
   * The column <code>public.permissions.description</code>.
   */
  val DESCRIPTION: TableField[PermissionsRecord, String] = createField(DSL.name("description"), SQLDataType.VARCHAR(255), "")

  private def this(alias: Name, aliased: Table[PermissionsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.permissions</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.Permissions.PERMISSIONS)

  /**
   * Create an aliased <code>public.permissions</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.Permissions.PERMISSIONS)

  /**
   * Create a <code>public.permissions</code> table reference
   */
  def this() = this(DSL.name("permissions"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, PermissionsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.Permissions.PERMISSIONS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[PermissionsRecord] = Keys.PERMISSIONS_PKEY

  override def getUniqueKeys: List[ UniqueKey[PermissionsRecord] ] = Arrays.asList[ UniqueKey[PermissionsRecord] ](Keys.PERMISSIONS_NAME_KEY)
  override def as(alias: String): Permissions = new Permissions(DSL.name(alias), this)
  override def as(alias: Name): Permissions = new Permissions(alias, this)
  override def as(alias: Table[_]): Permissions = new Permissions(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): Permissions = new Permissions(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): Permissions = new Permissions(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): Permissions = new Permissions(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row3 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row3[UUID, String, String] = super.fieldsRow.asInstanceOf[ Row3[UUID, String, String] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, String, String) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, String, String) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3()))
}
