/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.PricingRulesRecord

import java.lang.Class
import java.lang.String
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object PricingRules {

  /**
   * The reference instance of <code>public.pricing_rules</code>
   */
  val PRICING_RULES = new PricingRules
}

/**
 * This class is generated by jOOQ.
 */
class PricingRules(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, PricingRulesRecord],
  aliased: Table[PricingRulesRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[PricingRulesRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[PricingRulesRecord] = classOf[PricingRulesRecord]

  /**
   * The column <code>public.pricing_rules.id</code>.
   */
  val ID: TableField[PricingRulesRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.pricing_rules.rule_type</code>.
   */
  val RULE_TYPE: TableField[PricingRulesRecord, String] = createField(DSL.name("rule_type"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.pricing_rules.rate</code>.
   */
  val RATE: TableField[PricingRulesRecord, BigDecimal] = createField(DSL.name("rate"), SQLDataType.NUMERIC(10, 2).nullable(false), "")

  /**
   * The column <code>public.pricing_rules.vehicle_type</code>.
   */
  val VEHICLE_TYPE: TableField[PricingRulesRecord, String] = createField(DSL.name("vehicle_type"), SQLDataType.VARCHAR(50), "")

  /**
   * The column <code>public.pricing_rules.lot_id</code>.
   */
  val LOT_ID: TableField[PricingRulesRecord, UUID] = createField(DSL.name("lot_id"), SQLDataType.UUID, "")

  /**
   * The column <code>public.pricing_rules.created_at</code>.
   */
  val CREATED_AT: TableField[PricingRulesRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.pricing_rules.updated_at</code>.
   */
  val UPDATED_AT: TableField[PricingRulesRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  private def this(alias: Name, aliased: Table[PricingRulesRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.pricing_rules</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.PricingRules.PRICING_RULES)

  /**
   * Create an aliased <code>public.pricing_rules</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.PricingRules.PRICING_RULES)

  /**
   * Create a <code>public.pricing_rules</code> table reference
   */
  def this() = this(DSL.name("pricing_rules"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, PricingRulesRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.PricingRules.PRICING_RULES, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[PricingRulesRecord] = Keys.PRICING_RULES_PKEY

  override def getReferences: List[ ForeignKey[PricingRulesRecord, _] ] = Arrays.asList[ ForeignKey[PricingRulesRecord, _] ](Keys.PRICING_RULES__PRICING_RULES_LOT_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.parking_lots</code> table.
   */
  lazy val parkingLots: ParkingLots = { new ParkingLots(this, Keys.PRICING_RULES__PRICING_RULES_LOT_ID_FKEY) }
  override def as(alias: String): PricingRules = new PricingRules(DSL.name(alias), this)
  override def as(alias: Name): PricingRules = new PricingRules(alias, this)
  override def as(alias: Table[_]): PricingRules = new PricingRules(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): PricingRules = new PricingRules(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): PricingRules = new PricingRules(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): PricingRules = new PricingRules(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row7 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row7[UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, String, BigDecimal, String, UUID, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))
}
