/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Indexes
import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.ReservationsRecord

import java.lang.Class
import java.lang.String
import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Check
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object Reservations {

  /**
   * The reference instance of <code>public.reservations</code>
   */
  val RESERVATIONS = new Reservations
}

/**
 * This class is generated by jOOQ.
 */
class Reservations(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, ReservationsRecord],
  aliased: Table[ReservationsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[ReservationsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[ReservationsRecord] = classOf[ReservationsRecord]

  /**
   * The column <code>public.reservations.id</code>.
   */
  val ID: TableField[ReservationsRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.reservations.user_id</code>.
   */
  val USER_ID: TableField[ReservationsRecord, UUID] = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.reservations.space_id</code>.
   */
  val SPACE_ID: TableField[ReservationsRecord, UUID] = createField(DSL.name("space_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.reservations.start_time</code>.
   */
  val START_TIME: TableField[ReservationsRecord, OffsetDateTime] = createField(DSL.name("start_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), "")

  /**
   * The column <code>public.reservations.end_time</code>.
   */
  val END_TIME: TableField[ReservationsRecord, OffsetDateTime] = createField(DSL.name("end_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), "")

  /**
   * The column <code>public.reservations.status</code>.
   */
  val STATUS: TableField[ReservationsRecord, String] = createField(DSL.name("status"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("'CONFIRMED'::character varying"), SQLDataType.VARCHAR)), "")

  /**
   * The column <code>public.reservations.fee</code>.
   */
  val FEE: TableField[ReservationsRecord, BigDecimal] = createField(DSL.name("fee"), SQLDataType.NUMERIC(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0.00"), SQLDataType.NUMERIC)), "")

  /**
   * The column <code>public.reservations.created_at</code>.
   */
  val CREATED_AT: TableField[ReservationsRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.reservations.updated_at</code>.
   */
  val UPDATED_AT: TableField[ReservationsRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  private def this(alias: Name, aliased: Table[ReservationsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.reservations</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.Reservations.RESERVATIONS)

  /**
   * Create an aliased <code>public.reservations</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.Reservations.RESERVATIONS)

  /**
   * Create a <code>public.reservations</code> table reference
   */
  def this() = this(DSL.name("reservations"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, ReservationsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.Reservations.RESERVATIONS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getIndexes: List[Index] = Arrays.asList[ Index ](Indexes.IDX_RESERVATIONS_SPACE_TIME)

  override def getPrimaryKey: UniqueKey[ReservationsRecord] = Keys.RESERVATIONS_PKEY

  override def getReferences: List[ ForeignKey[ReservationsRecord, _] ] = Arrays.asList[ ForeignKey[ReservationsRecord, _] ](Keys.RESERVATIONS__RESERVATIONS_USER_ID_FKEY, Keys.RESERVATIONS__RESERVATIONS_SPACE_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.users</code> table.
   */
  lazy val users: Users = { new Users(this, Keys.RESERVATIONS__RESERVATIONS_USER_ID_FKEY) }

  /**
   * Get the implicit join path to the <code>public.parking_spaces</code> table.
   */
  lazy val parkingSpaces: ParkingSpaces = { new ParkingSpaces(this, Keys.RESERVATIONS__RESERVATIONS_SPACE_ID_FKEY) }
  override def getChecks: List[ Check[ReservationsRecord] ] = Arrays.asList[ Check[ReservationsRecord] ](
    Internal.createCheck(this, DSL.name("chk_status"), "(((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))", true),
    Internal.createCheck(this, DSL.name("chk_times"), "((start_time < end_time))", true)
  )
  override def as(alias: String): Reservations = new Reservations(DSL.name(alias), this)
  override def as(alias: Name): Reservations = new Reservations(alias, this)
  override def as(alias: Table[_]): Reservations = new Reservations(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): Reservations = new Reservations(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): Reservations = new Reservations(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): Reservations = new Reservations(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row9 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row9[UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8(), r.value9()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, String, BigDecimal, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8(), r.value9()))
}
