/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.RolesRecord

import java.lang.Class
import java.lang.String
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object Roles {

  /**
   * The reference instance of <code>public.roles</code>
   */
  val ROLES = new Roles
}

/**
 * This class is generated by jOOQ.
 */
class Roles(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, RolesRecord],
  aliased: Table[RolesRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[RolesRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[RolesRecord] = classOf[RolesRecord]

  /**
   * The column <code>public.roles.id</code>.
   */
  val ID: TableField[RolesRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.roles.name</code>.
   */
  val NAME: TableField[RolesRecord, String] = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.roles.description</code>.
   */
  val DESCRIPTION: TableField[RolesRecord, String] = createField(DSL.name("description"), SQLDataType.VARCHAR(255), "")

  private def this(alias: Name, aliased: Table[RolesRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.roles</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.Roles.ROLES)

  /**
   * Create an aliased <code>public.roles</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.Roles.ROLES)

  /**
   * Create a <code>public.roles</code> table reference
   */
  def this() = this(DSL.name("roles"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, RolesRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.Roles.ROLES, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[RolesRecord] = Keys.ROLES_PKEY

  override def getUniqueKeys: List[ UniqueKey[RolesRecord] ] = Arrays.asList[ UniqueKey[RolesRecord] ](Keys.ROLES_NAME_KEY)
  override def as(alias: String): Roles = new Roles(DSL.name(alias), this)
  override def as(alias: Name): Roles = new Roles(alias, this)
  override def as(alias: Table[_]): Roles = new Roles(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): Roles = new Roles(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): Roles = new Roles(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): Roles = new Roles(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row3 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row3[UUID, String, String] = super.fieldsRow.asInstanceOf[ Row3[UUID, String, String] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, String, String) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, String, String) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3()))
}
