/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.RolePermissionsRecord

import java.lang.Class
import java.lang.String
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object RolePermissions {

  /**
   * The reference instance of <code>public.role_permissions</code>
   */
  val ROLE_PERMISSIONS = new RolePermissions
}

/**
 * This class is generated by jOOQ.
 */
class RolePermissions(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, RolePermissionsRecord],
  aliased: Table[RolePermissionsRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[RolePermissionsRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[RolePermissionsRecord] = classOf[RolePermissionsRecord]

  /**
   * The column <code>public.role_permissions.role_id</code>.
   */
  val ROLE_ID: TableField[RolePermissionsRecord, UUID] = createField(DSL.name("role_id"), SQLDataType.UUID.nullable(false), "")

  /**
   * The column <code>public.role_permissions.permission_id</code>.
   */
  val PERMISSION_ID: TableField[RolePermissionsRecord, UUID] = createField(DSL.name("permission_id"), SQLDataType.UUID.nullable(false), "")

  private def this(alias: Name, aliased: Table[RolePermissionsRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.role_permissions</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.RolePermissions.ROLE_PERMISSIONS)

  /**
   * Create an aliased <code>public.role_permissions</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.RolePermissions.ROLE_PERMISSIONS)

  /**
   * Create a <code>public.role_permissions</code> table reference
   */
  def this() = this(DSL.name("role_permissions"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, RolePermissionsRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.RolePermissions.ROLE_PERMISSIONS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[RolePermissionsRecord] = Keys.ROLE_PERMISSIONS_PKEY

  override def getReferences: List[ ForeignKey[RolePermissionsRecord, _] ] = Arrays.asList[ ForeignKey[RolePermissionsRecord, _] ](Keys.ROLE_PERMISSIONS__ROLE_PERMISSIONS_ROLE_ID_FKEY, Keys.ROLE_PERMISSIONS__ROLE_PERMISSIONS_PERMISSION_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.roles</code> table.
   */
  lazy val roles: Roles = { new Roles(this, Keys.ROLE_PERMISSIONS__ROLE_PERMISSIONS_ROLE_ID_FKEY) }

  /**
   * Get the implicit join path to the <code>public.permissions</code> table.
   */
  lazy val permissions: Permissions = { new Permissions(this, Keys.ROLE_PERMISSIONS__ROLE_PERMISSIONS_PERMISSION_ID_FKEY) }
  override def as(alias: String): RolePermissions = new RolePermissions(DSL.name(alias), this)
  override def as(alias: Name): RolePermissions = new RolePermissions(alias, this)
  override def as(alias: Table[_]): RolePermissions = new RolePermissions(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): RolePermissions = new RolePermissions(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): RolePermissions = new RolePermissions(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): RolePermissions = new RolePermissions(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row2 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row2[UUID, UUID] = super.fieldsRow.asInstanceOf[ Row2[UUID, UUID] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, UUID) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, UUID) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2()))
}
