/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.UsersRecord

import java.lang.Class
import java.lang.String
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object Users {

  /**
   * The reference instance of <code>public.users</code>
   */
  val USERS = new Users
}

/**
 * This class is generated by jOOQ.
 */
class Users(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, UsersRecord],
  aliased: Table[UsersRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[UsersRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[UsersRecord] = classOf[UsersRecord]

  /**
   * The column <code>public.users.id</code>.
   */
  val ID: TableField[UsersRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.users.name</code>.
   */
  val NAME: TableField[UsersRecord, String] = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), "")

  /**
   * The column <code>public.users.email</code>.
   */
  val EMAIL: TableField[UsersRecord, String] = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), "")

  /**
   * The column <code>public.users.password_hash</code>.
   */
  val PASSWORD_HASH: TableField[UsersRecord, String] = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), "")

  /**
   * The column <code>public.users.created_at</code>.
   */
  val CREATED_AT: TableField[UsersRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.users.updated_at</code>.
   */
  val UPDATED_AT: TableField[UsersRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.users.deleted_at</code>.
   */
  val DELETED_AT: TableField[UsersRecord, OffsetDateTime] = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), "")

  /**
   * The column <code>public.users.role_id</code>.
   */
  val ROLE_ID: TableField[UsersRecord, UUID] = createField(DSL.name("role_id"), SQLDataType.UUID, "")

  private def this(alias: Name, aliased: Table[UsersRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.users</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.Users.USERS)

  /**
   * Create an aliased <code>public.users</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.Users.USERS)

  /**
   * Create a <code>public.users</code> table reference
   */
  def this() = this(DSL.name("users"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, UsersRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.Users.USERS, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[UsersRecord] = Keys.USERS_PKEY

  override def getUniqueKeys: List[ UniqueKey[UsersRecord] ] = Arrays.asList[ UniqueKey[UsersRecord] ](Keys.USERS_EMAIL_KEY)

  override def getReferences: List[ ForeignKey[UsersRecord, _] ] = Arrays.asList[ ForeignKey[UsersRecord, _] ](Keys.USERS__USERS_ROLE_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.roles</code> table.
   */
  lazy val roles: Roles = { new Roles(this, Keys.USERS__USERS_ROLE_ID_FKEY) }
  override def as(alias: String): Users = new Users(DSL.name(alias), this)
  override def as(alias: Name): Users = new Users(alias, this)
  override def as(alias: Table[_]): Users = new Users(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): Users = new Users(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): Users = new Users(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): Users = new Users(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row8 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row8[UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID] = super.fieldsRow.asInstanceOf[ Row8[UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7(), r.value8()))
}
