/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq.tables


import com.metropolisparking.jooq.Keys
import com.metropolisparking.jooq.Public
import com.metropolisparking.jooq.tables.records.VehiclesRecord

import java.lang.Class
import java.lang.String
import java.time.OffsetDateTime
import java.util.Arrays
import java.util.List
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object Vehicles {

  /**
   * The reference instance of <code>public.vehicles</code>
   */
  val VEHICLES = new Vehicles
}

/**
 * This class is generated by jOOQ.
 */
class Vehicles(
  alias: Name,
  child: Table[_ <: Record],
  path: ForeignKey[_ <: Record, VehiclesRecord],
  aliased: Table[VehiclesRecord],
  parameters: Array[ Field[_] ]
)
extends TableImpl[VehiclesRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[VehiclesRecord] = classOf[VehiclesRecord]

  /**
   * The column <code>public.vehicles.id</code>.
   */
  val ID: TableField[VehiclesRecord, UUID] = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), "")

  /**
   * The column <code>public.vehicles.plate_number</code>.
   */
  val PLATE_NUMBER: TableField[VehiclesRecord, String] = createField(DSL.name("plate_number"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.vehicles.type</code>.
   */
  val TYPE: TableField[VehiclesRecord, String] = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * The column <code>public.vehicles.owner_id</code>.
   */
  val OWNER_ID: TableField[VehiclesRecord, UUID] = createField(DSL.name("owner_id"), SQLDataType.UUID, "")

  /**
   * The column <code>public.vehicles.created_at</code>.
   */
  val CREATED_AT: TableField[VehiclesRecord, OffsetDateTime] = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.vehicles.updated_at</code>.
   */
  val UPDATED_AT: TableField[VehiclesRecord, OffsetDateTime] = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), "")

  /**
   * The column <code>public.vehicles.deleted_at</code>.
   */
  val DELETED_AT: TableField[VehiclesRecord, OffsetDateTime] = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), "")

  private def this(alias: Name, aliased: Table[VehiclesRecord]) = this(alias, null, null, aliased, null)

  /**
   * Create an aliased <code>public.vehicles</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), com.metropolisparking.jooq.tables.Vehicles.VEHICLES)

  /**
   * Create an aliased <code>public.vehicles</code> table reference
   */
  def this(alias: Name) = this(alias, com.metropolisparking.jooq.tables.Vehicles.VEHICLES)

  /**
   * Create a <code>public.vehicles</code> table reference
   */
  def this() = this(DSL.name("vehicles"), null)

  def this(child: Table[_ <: Record], key: ForeignKey[_ <: Record, VehiclesRecord]) = this(Internal.createPathAlias(child, key), child, key, com.metropolisparking.jooq.tables.Vehicles.VEHICLES, null)

  override def getSchema: Schema = if (aliased()) null else Public.PUBLIC

  override def getPrimaryKey: UniqueKey[VehiclesRecord] = Keys.VEHICLES_PKEY

  override def getUniqueKeys: List[ UniqueKey[VehiclesRecord] ] = Arrays.asList[ UniqueKey[VehiclesRecord] ](Keys.VEHICLES_PLATE_NUMBER_KEY)

  override def getReferences: List[ ForeignKey[VehiclesRecord, _] ] = Arrays.asList[ ForeignKey[VehiclesRecord, _] ](Keys.VEHICLES__VEHICLES_OWNER_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.users</code> table.
   */
  lazy val users: Users = { new Users(this, Keys.VEHICLES__VEHICLES_OWNER_ID_FKEY) }
  override def as(alias: String): Vehicles = new Vehicles(DSL.name(alias), this)
  override def as(alias: Name): Vehicles = new Vehicles(alias, this)
  override def as(alias: Table[_]): Vehicles = new Vehicles(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): Vehicles = new Vehicles(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): Vehicles = new Vehicles(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[_]): Vehicles = new Vehicles(name.getQualifiedName(), null)

  // -------------------------------------------------------------------------
  // Row7 type methods
  // -------------------------------------------------------------------------
  override def fieldsRow: Row7[UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime] = super.fieldsRow.asInstanceOf[ Row7[UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime] ]

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
   */
  def mapping[U](from: (UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))

  /**
   * Convenience mapping calling {@link SelectField#convertFrom(Class,
   * Function)}.
   */
  def mapping[U](toType: Class[U], from: (UUID, String, String, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime) => U): SelectField[U] = convertFrom(toType,r => from.apply(r.value1(), r.value2(), r.value3(), r.value4(), r.value5(), r.value6(), r.value7()))
}
