/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq


import com.metropolisparking.jooq.tables.Reservations

import org.jooq.Index
import org.jooq.OrderField
import org.jooq.impl.DSL
import org.jooq.impl.Internal


/**
 * A class modelling indexes of tables in public.
 */
object Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  val IDX_RESERVATIONS_SPACE_TIME: Index = Internal.createIndex(DSL.name("idx_reservations_space_time"), Reservations.RESERVATIONS, Array[OrderField [_] ](Reservations.RESERVATIONS.SPACE_ID, Reservations.RESERVATIONS.START_TIME, Reservations.RESERVATIONS.END_TIME), false)
}
