/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq


import com.metropolisparking.jooq.tables.AuditLogs
import com.metropolisparking.jooq.tables.ParkingLevels
import com.metropolisparking.jooq.tables.ParkingLots
import com.metropolisparking.jooq.tables.ParkingSessions
import com.metropolisparking.jooq.tables.ParkingSpaces
import com.metropolisparking.jooq.tables.Payments
import com.metropolisparking.jooq.tables.Permissions
import com.metropolisparking.jooq.tables.PricingRules
import com.metropolisparking.jooq.tables.RolePermissions
import com.metropolisparking.jooq.tables.Roles
import com.metropolisparking.jooq.tables.Users
import com.metropolisparking.jooq.tables.Vehicles
import com.metropolisparking.jooq.tables.records.AuditLogsRecord
import com.metropolisparking.jooq.tables.records.ParkingLevelsRecord
import com.metropolisparking.jooq.tables.records.ParkingLotsRecord
import com.metropolisparking.jooq.tables.records.ParkingSessionsRecord
import com.metropolisparking.jooq.tables.records.ParkingSpacesRecord
import com.metropolisparking.jooq.tables.records.PaymentsRecord
import com.metropolisparking.jooq.tables.records.PermissionsRecord
import com.metropolisparking.jooq.tables.records.PricingRulesRecord
import com.metropolisparking.jooq.tables.records.RolePermissionsRecord
import com.metropolisparking.jooq.tables.records.RolesRecord
import com.metropolisparking.jooq.tables.records.UsersRecord
import com.metropolisparking.jooq.tables.records.VehiclesRecord

import org.jooq.ForeignKey
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
object Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  val AUDIT_LOGS_PKEY: UniqueKey[AuditLogsRecord] = Internal.createUniqueKey(AuditLogs.AUDIT_LOGS, DSL.name("audit_logs_pkey"), Array(AuditLogs.AUDIT_LOGS.ID).asInstanceOf[Array[TableField[AuditLogsRecord, _] ] ], true)
  val PARKING_LEVELS_LOT_ID_LEVEL_NUMBER_KEY: UniqueKey[ParkingLevelsRecord] = Internal.createUniqueKey(ParkingLevels.PARKING_LEVELS, DSL.name("parking_levels_lot_id_level_number_key"), Array(ParkingLevels.PARKING_LEVELS.LOT_ID, ParkingLevels.PARKING_LEVELS.LEVEL_NUMBER).asInstanceOf[Array[TableField[ParkingLevelsRecord, _] ] ], true)
  val PARKING_LEVELS_PKEY: UniqueKey[ParkingLevelsRecord] = Internal.createUniqueKey(ParkingLevels.PARKING_LEVELS, DSL.name("parking_levels_pkey"), Array(ParkingLevels.PARKING_LEVELS.ID).asInstanceOf[Array[TableField[ParkingLevelsRecord, _] ] ], true)
  val PARKING_LOTS_PKEY: UniqueKey[ParkingLotsRecord] = Internal.createUniqueKey(ParkingLots.PARKING_LOTS, DSL.name("parking_lots_pkey"), Array(ParkingLots.PARKING_LOTS.ID).asInstanceOf[Array[TableField[ParkingLotsRecord, _] ] ], true)
  val PARKING_SESSIONS_PKEY: UniqueKey[ParkingSessionsRecord] = Internal.createUniqueKey(ParkingSessions.PARKING_SESSIONS, DSL.name("parking_sessions_pkey"), Array(ParkingSessions.PARKING_SESSIONS.ID).asInstanceOf[Array[TableField[ParkingSessionsRecord, _] ] ], true)
  val PARKING_SPACES_LEVEL_ID_SPACE_NUMBER_KEY: UniqueKey[ParkingSpacesRecord] = Internal.createUniqueKey(ParkingSpaces.PARKING_SPACES, DSL.name("parking_spaces_level_id_space_number_key"), Array(ParkingSpaces.PARKING_SPACES.LEVEL_ID, ParkingSpaces.PARKING_SPACES.SPACE_NUMBER).asInstanceOf[Array[TableField[ParkingSpacesRecord, _] ] ], true)
  val PARKING_SPACES_PKEY: UniqueKey[ParkingSpacesRecord] = Internal.createUniqueKey(ParkingSpaces.PARKING_SPACES, DSL.name("parking_spaces_pkey"), Array(ParkingSpaces.PARKING_SPACES.ID).asInstanceOf[Array[TableField[ParkingSpacesRecord, _] ] ], true)
  val PAYMENTS_PKEY: UniqueKey[PaymentsRecord] = Internal.createUniqueKey(Payments.PAYMENTS, DSL.name("payments_pkey"), Array(Payments.PAYMENTS.ID).asInstanceOf[Array[TableField[PaymentsRecord, _] ] ], true)
  val PERMISSIONS_NAME_KEY: UniqueKey[PermissionsRecord] = Internal.createUniqueKey(Permissions.PERMISSIONS, DSL.name("permissions_name_key"), Array(Permissions.PERMISSIONS.NAME).asInstanceOf[Array[TableField[PermissionsRecord, _] ] ], true)
  val PERMISSIONS_PKEY: UniqueKey[PermissionsRecord] = Internal.createUniqueKey(Permissions.PERMISSIONS, DSL.name("permissions_pkey"), Array(Permissions.PERMISSIONS.ID).asInstanceOf[Array[TableField[PermissionsRecord, _] ] ], true)
  val PRICING_RULES_PKEY: UniqueKey[PricingRulesRecord] = Internal.createUniqueKey(PricingRules.PRICING_RULES, DSL.name("pricing_rules_pkey"), Array(PricingRules.PRICING_RULES.ID).asInstanceOf[Array[TableField[PricingRulesRecord, _] ] ], true)
  val ROLE_PERMISSIONS_PKEY: UniqueKey[RolePermissionsRecord] = Internal.createUniqueKey(RolePermissions.ROLE_PERMISSIONS, DSL.name("role_permissions_pkey"), Array(RolePermissions.ROLE_PERMISSIONS.ROLE_ID, RolePermissions.ROLE_PERMISSIONS.PERMISSION_ID).asInstanceOf[Array[TableField[RolePermissionsRecord, _] ] ], true)
  val ROLES_NAME_KEY: UniqueKey[RolesRecord] = Internal.createUniqueKey(Roles.ROLES, DSL.name("roles_name_key"), Array(Roles.ROLES.NAME).asInstanceOf[Array[TableField[RolesRecord, _] ] ], true)
  val ROLES_PKEY: UniqueKey[RolesRecord] = Internal.createUniqueKey(Roles.ROLES, DSL.name("roles_pkey"), Array(Roles.ROLES.ID).asInstanceOf[Array[TableField[RolesRecord, _] ] ], true)
  val USERS_EMAIL_KEY: UniqueKey[UsersRecord] = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), Array(Users.USERS.EMAIL).asInstanceOf[Array[TableField[UsersRecord, _] ] ], true)
  val USERS_PKEY: UniqueKey[UsersRecord] = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), Array(Users.USERS.ID).asInstanceOf[Array[TableField[UsersRecord, _] ] ], true)
  val VEHICLES_PKEY: UniqueKey[VehiclesRecord] = Internal.createUniqueKey(Vehicles.VEHICLES, DSL.name("vehicles_pkey"), Array(Vehicles.VEHICLES.ID).asInstanceOf[Array[TableField[VehiclesRecord, _] ] ], true)
  val VEHICLES_PLATE_NUMBER_KEY: UniqueKey[VehiclesRecord] = Internal.createUniqueKey(Vehicles.VEHICLES, DSL.name("vehicles_plate_number_key"), Array(Vehicles.VEHICLES.PLATE_NUMBER).asInstanceOf[Array[TableField[VehiclesRecord, _] ] ], true)

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  val AUDIT_LOGS__AUDIT_LOGS_USER_ID_FKEY: ForeignKey[AuditLogsRecord, UsersRecord] = Internal.createForeignKey(AuditLogs.AUDIT_LOGS, DSL.name("audit_logs_user_id_fkey"), Array(AuditLogs.AUDIT_LOGS.USER_ID).asInstanceOf[Array[TableField[AuditLogsRecord, _] ] ], Keys.USERS_PKEY, Array(Users.USERS.ID).asInstanceOf[Array[TableField[UsersRecord, _] ] ], true)
  val PARKING_LEVELS__PARKING_LEVELS_LOT_ID_FKEY: ForeignKey[ParkingLevelsRecord, ParkingLotsRecord] = Internal.createForeignKey(ParkingLevels.PARKING_LEVELS, DSL.name("parking_levels_lot_id_fkey"), Array(ParkingLevels.PARKING_LEVELS.LOT_ID).asInstanceOf[Array[TableField[ParkingLevelsRecord, _] ] ], Keys.PARKING_LOTS_PKEY, Array(ParkingLots.PARKING_LOTS.ID).asInstanceOf[Array[TableField[ParkingLotsRecord, _] ] ], true)
  val PARKING_SESSIONS__PARKING_SESSIONS_SPACE_ID_FKEY: ForeignKey[ParkingSessionsRecord, ParkingSpacesRecord] = Internal.createForeignKey(ParkingSessions.PARKING_SESSIONS, DSL.name("parking_sessions_space_id_fkey"), Array(ParkingSessions.PARKING_SESSIONS.SPACE_ID).asInstanceOf[Array[TableField[ParkingSessionsRecord, _] ] ], Keys.PARKING_SPACES_PKEY, Array(ParkingSpaces.PARKING_SPACES.ID).asInstanceOf[Array[TableField[ParkingSpacesRecord, _] ] ], true)
  val PARKING_SESSIONS__PARKING_SESSIONS_VEHICLE_ID_FKEY: ForeignKey[ParkingSessionsRecord, VehiclesRecord] = Internal.createForeignKey(ParkingSessions.PARKING_SESSIONS, DSL.name("parking_sessions_vehicle_id_fkey"), Array(ParkingSessions.PARKING_SESSIONS.VEHICLE_ID).asInstanceOf[Array[TableField[ParkingSessionsRecord, _] ] ], Keys.VEHICLES_PKEY, Array(Vehicles.VEHICLES.ID).asInstanceOf[Array[TableField[VehiclesRecord, _] ] ], true)
  val PARKING_SPACES__PARKING_SPACES_LEVEL_ID_FKEY: ForeignKey[ParkingSpacesRecord, ParkingLevelsRecord] = Internal.createForeignKey(ParkingSpaces.PARKING_SPACES, DSL.name("parking_spaces_level_id_fkey"), Array(ParkingSpaces.PARKING_SPACES.LEVEL_ID).asInstanceOf[Array[TableField[ParkingSpacesRecord, _] ] ], Keys.PARKING_LEVELS_PKEY, Array(ParkingLevels.PARKING_LEVELS.ID).asInstanceOf[Array[TableField[ParkingLevelsRecord, _] ] ], true)
  val PARKING_SPACES__PARKING_SPACES_LOT_ID_FKEY: ForeignKey[ParkingSpacesRecord, ParkingLotsRecord] = Internal.createForeignKey(ParkingSpaces.PARKING_SPACES, DSL.name("parking_spaces_lot_id_fkey"), Array(ParkingSpaces.PARKING_SPACES.LOT_ID).asInstanceOf[Array[TableField[ParkingSpacesRecord, _] ] ], Keys.PARKING_LOTS_PKEY, Array(ParkingLots.PARKING_LOTS.ID).asInstanceOf[Array[TableField[ParkingLotsRecord, _] ] ], true)
  val PAYMENTS__PAYMENTS_SESSION_ID_FKEY: ForeignKey[PaymentsRecord, ParkingSessionsRecord] = Internal.createForeignKey(Payments.PAYMENTS, DSL.name("payments_session_id_fkey"), Array(Payments.PAYMENTS.SESSION_ID).asInstanceOf[Array[TableField[PaymentsRecord, _] ] ], Keys.PARKING_SESSIONS_PKEY, Array(ParkingSessions.PARKING_SESSIONS.ID).asInstanceOf[Array[TableField[ParkingSessionsRecord, _] ] ], true)
  val PRICING_RULES__PRICING_RULES_LOT_ID_FKEY: ForeignKey[PricingRulesRecord, ParkingLotsRecord] = Internal.createForeignKey(PricingRules.PRICING_RULES, DSL.name("pricing_rules_lot_id_fkey"), Array(PricingRules.PRICING_RULES.LOT_ID).asInstanceOf[Array[TableField[PricingRulesRecord, _] ] ], Keys.PARKING_LOTS_PKEY, Array(ParkingLots.PARKING_LOTS.ID).asInstanceOf[Array[TableField[ParkingLotsRecord, _] ] ], true)
  val ROLE_PERMISSIONS__ROLE_PERMISSIONS_PERMISSION_ID_FKEY: ForeignKey[RolePermissionsRecord, PermissionsRecord] = Internal.createForeignKey(RolePermissions.ROLE_PERMISSIONS, DSL.name("role_permissions_permission_id_fkey"), Array(RolePermissions.ROLE_PERMISSIONS.PERMISSION_ID).asInstanceOf[Array[TableField[RolePermissionsRecord, _] ] ], Keys.PERMISSIONS_PKEY, Array(Permissions.PERMISSIONS.ID).asInstanceOf[Array[TableField[PermissionsRecord, _] ] ], true)
  val ROLE_PERMISSIONS__ROLE_PERMISSIONS_ROLE_ID_FKEY: ForeignKey[RolePermissionsRecord, RolesRecord] = Internal.createForeignKey(RolePermissions.ROLE_PERMISSIONS, DSL.name("role_permissions_role_id_fkey"), Array(RolePermissions.ROLE_PERMISSIONS.ROLE_ID).asInstanceOf[Array[TableField[RolePermissionsRecord, _] ] ], Keys.ROLES_PKEY, Array(Roles.ROLES.ID).asInstanceOf[Array[TableField[RolesRecord, _] ] ], true)
  val USERS__USERS_ROLE_ID_FKEY: ForeignKey[UsersRecord, RolesRecord] = Internal.createForeignKey(Users.USERS, DSL.name("users_role_id_fkey"), Array(Users.USERS.ROLE_ID).asInstanceOf[Array[TableField[UsersRecord, _] ] ], Keys.ROLES_PKEY, Array(Roles.ROLES.ID).asInstanceOf[Array[TableField[RolesRecord, _] ] ], true)
  val VEHICLES__VEHICLES_OWNER_ID_FKEY: ForeignKey[VehiclesRecord, UsersRecord] = Internal.createForeignKey(Vehicles.VEHICLES, DSL.name("vehicles_owner_id_fkey"), Array(Vehicles.VEHICLES.OWNER_ID).asInstanceOf[Array[TableField[VehiclesRecord, _] ] ], Keys.USERS_PKEY, Array(Users.USERS.ID).asInstanceOf[Array[TableField[UsersRecord, _] ] ], true)
}
