/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq


import com.metropolisparking.jooq.tables.AuditLogs
import com.metropolisparking.jooq.tables.ParkingLevels
import com.metropolisparking.jooq.tables.ParkingLots
import com.metropolisparking.jooq.tables.ParkingSessions
import com.metropolisparking.jooq.tables.ParkingSpaces
import com.metropolisparking.jooq.tables.Payments
import com.metropolisparking.jooq.tables.Permissions
import com.metropolisparking.jooq.tables.PricingRules
import com.metropolisparking.jooq.tables.RolePermissions
import com.metropolisparking.jooq.tables.Roles
import com.metropolisparking.jooq.tables.Users
import com.metropolisparking.jooq.tables.Vehicles

import java.util.Arrays
import java.util.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


object Public {

  /**
   * The reference instance of <code>public</code>
   */
  val PUBLIC = new Public
}

/**
 * This class is generated by jOOQ.
 */
class Public extends SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {

  /**
   * The table <code>public.audit_logs</code>.
   */
  def AUDIT_LOGS = AuditLogs.AUDIT_LOGS

  /**
   * The table <code>public.parking_levels</code>.
   */
  def PARKING_LEVELS = ParkingLevels.PARKING_LEVELS

  /**
   * The table <code>public.parking_lots</code>.
   */
  def PARKING_LOTS = ParkingLots.PARKING_LOTS

  /**
   * The table <code>public.parking_sessions</code>.
   */
  def PARKING_SESSIONS = ParkingSessions.PARKING_SESSIONS

  /**
   * The table <code>public.parking_spaces</code>.
   */
  def PARKING_SPACES = ParkingSpaces.PARKING_SPACES

  /**
   * The table <code>public.payments</code>.
   */
  def PAYMENTS = Payments.PAYMENTS

  /**
   * The table <code>public.permissions</code>.
   */
  def PERMISSIONS = Permissions.PERMISSIONS

  /**
   * The table <code>public.pricing_rules</code>.
   */
  def PRICING_RULES = PricingRules.PRICING_RULES

  /**
   * The table <code>public.role_permissions</code>.
   */
  def ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS

  /**
   * The table <code>public.roles</code>.
   */
  def ROLES = Roles.ROLES

  /**
   * The table <code>public.users</code>.
   */
  def USERS = Users.USERS

  /**
   * The table <code>public.vehicles</code>.
   */
  def VEHICLES = Vehicles.VEHICLES

  override def getCatalog: Catalog = DefaultCatalog.DEFAULT_CATALOG

  override def getTables: List[Table[_]] = Arrays.asList[Table[_]](
    AuditLogs.AUDIT_LOGS,
    ParkingLevels.PARKING_LEVELS,
    ParkingLots.PARKING_LOTS,
    ParkingSessions.PARKING_SESSIONS,
    ParkingSpaces.PARKING_SPACES,
    Payments.PAYMENTS,
    Permissions.PERMISSIONS,
    PricingRules.PRICING_RULES,
    RolePermissions.ROLE_PERMISSIONS,
    Roles.ROLES,
    Users.USERS,
    Vehicles.VEHICLES
  )
}
