/*
 * This file is generated by jOOQ.
 */
package com.metropolisparking.jooq


import com.metropolisparking.jooq.tables.AuditLogs
import com.metropolisparking.jooq.tables.ParkingLevels
import com.metropolisparking.jooq.tables.ParkingLots
import com.metropolisparking.jooq.tables.ParkingSessions
import com.metropolisparking.jooq.tables.ParkingSpaces
import com.metropolisparking.jooq.tables.Payments
import com.metropolisparking.jooq.tables.Permissions
import com.metropolisparking.jooq.tables.PricingRules
import com.metropolisparking.jooq.tables.RolePermissions
import com.metropolisparking.jooq.tables.Roles
import com.metropolisparking.jooq.tables.Users
import com.metropolisparking.jooq.tables.Vehicles


/**
 * Convenience access to all tables in public.
 */
object Tables {

  /**
   * The table <code>public.audit_logs</code>.
   */
  def AUDIT_LOGS = AuditLogs.AUDIT_LOGS

  /**
   * The table <code>public.parking_levels</code>.
   */
  def PARKING_LEVELS = ParkingLevels.PARKING_LEVELS

  /**
   * The table <code>public.parking_lots</code>.
   */
  def PARKING_LOTS = ParkingLots.PARKING_LOTS

  /**
   * The table <code>public.parking_sessions</code>.
   */
  def PARKING_SESSIONS = ParkingSessions.PARKING_SESSIONS

  /**
   * The table <code>public.parking_spaces</code>.
   */
  def PARKING_SPACES = ParkingSpaces.PARKING_SPACES

  /**
   * The table <code>public.payments</code>.
   */
  def PAYMENTS = Payments.PAYMENTS

  /**
   * The table <code>public.permissions</code>.
   */
  def PERMISSIONS = Permissions.PERMISSIONS

  /**
   * The table <code>public.pricing_rules</code>.
   */
  def PRICING_RULES = PricingRules.PRICING_RULES

  /**
   * The table <code>public.role_permissions</code>.
   */
  def ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS

  /**
   * The table <code>public.roles</code>.
   */
  def ROLES = Roles.ROLES

  /**
   * The table <code>public.users</code>.
   */
  def USERS = Users.USERS

  /**
   * The table <code>public.vehicles</code>.
   */
  def VEHICLES = Vehicles.VEHICLES
}
