app-env = "local"
app-env = ${?APP_ENV}

http {
  host = "0.0.0.0"
  host = ${?HTTP_HOST}
  port = 8080
  port = ${?HTTP_PORT}
}

db {
  url = "jdbc:postgresql://localhost:5432/metropolis_parking"
  url = ${?DB_URL}
  username = "postgres"
  username = ${?DB_USERNAME}
  password = "password"
  password = ${?DB_PASSWORD}
}

jwt {
  secret = "super-secret-key-change-in-production"
  secret = ${?JWT_SECRET}
  expire-duration-seconds = 86400
  expire-duration-seconds = ${?JWT_EXPIRE_DURATION_SECONDS}
}
